
load("@aspect_rules_py//uv/private/pep517_whl:pep517_whl.bzl", "pep517_whl")
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py"],
    deps = ["@@aspect_rules_py++uv+project__pycross_pure_python//:build", "@@aspect_rules_py++uv+project__pycross_pure_python//:setuptools", "@@aspect_rules_py++uv+project__pycross_pure_python//:flit_core", "@@aspect_rules_py++uv+project__pycross_pure_python//:hatch_vcs", "@@aspect_rules_py++uv+project__pycross_pure_python//:hatchling", "@project__pycross_pure_python//private/build_deps:flit_core"],
    include_console_scripts = True,
)

pep517_whl(
    name = "whl",
    src = "@@aspect_rules_py++uv+sdist__tomli__cd45e1dc79c835ce//file:file",
    tool = ":build_tool",
    version = "2.2.1",
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
