
load("@aspect_rules_py//uv/private/pep517_whl:pep517_native_whl.bzl", "pep517_native_whl")
load("@aspect_rules_py//uv/private/pep517_whl:frontend.bzl", "pep517_frontend")
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py"],
    deps = ["@@aspect_rules_py++uv+project__pycross_numpy//:build", "@@aspect_rules_py++uv+project__pycross_numpy//:cython", "@@aspect_rules_py++uv+project__pycross_numpy//:meson_python", "@@aspect_rules_py++uv+project__pycross_numpy//:ninja", "@project__pycross_numpy//private/build_deps:cython", "@project__pycross_numpy//private/build_deps:meson_python"],
    include_console_scripts = True,
)

pep517_frontend(
    name = "frontend",
    actual = ":build_tool",
)

pep517_native_whl(
    name = "whl",
    src = "@@aspect_rules_py++uv+sdist__numpy__a48a113e6afea91f//file:file",
    tool = ":frontend",
    version = "2.5.1",
    config_settings = {
        "setup-args": ["-Dblas=none", "-Dlapack=none"],
    },
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
