load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")
load("//uv/private/constraints:defs.bzl", "INTERPRETERS", "MAJORS", "MINORS", "foreign_interpreter_tag")

def _generate_python_tags():
    tags = {}
    for interpreter in INTERPRETERS:
        for major in MAJORS:
            tags["{}{}".format(interpreter, major)] = True
            for minor in MINORS:
                tags["{}{}{}".format(interpreter, major, minor)] = True
    return tags

# Python tags with a config_setting target created by generate() in macro.bzl.
# Both sides derive from the same INTERPRETERS/MAJORS/MINORS constants, making
# "tag passes the filter but has no target" bugs impossible by construction.
PYTHON_TAGS = _generate_python_tags()

def supported_python(python_tag):
    """Predicate.

    Indicate whether a wheel python tag has a corresponding config_setting
    target generated by macro.bzl. Allows for filtering out of wheels for
    currently unsupported pythons (PyPy, Jython, IronPython, GraalPy) as well
    as malformed tags (e.g. `cp311_2` from a renamed wheel file) which would
    otherwise become select conditions on nonexistent targets.

    Args:
        python_tag (str): A wheel python tag

    Returns:
        bool; whether the python is supported and can be configured or not.

    """

    # See https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#python-tag
    return python_tag in PYTHON_TAGS

def filter_python_tags(wheel_name, python_tags):
    """Filter a wheel's python tags down to the supported allowlist.

    Tags for known foreign interpreters are dropped silently; anything else
    unsupported is dropped with a warning since it usually indicates a
    malformed (e.g. renamed) wheel filename.

    Args:
        wheel_name (str): The wheel filename, for diagnostics.
        python_tags (list of str): Parsed python tags of that wheel.

    Returns:
        list of str; the supported python tags in their original order.
    """
    kept = []
    for python_tag in python_tags:
        if supported_python(python_tag):
            kept.append(python_tag)
        elif not foreign_interpreter_tag(python_tag):
            # buildifier: disable=print
            print("WARNING: {}: python tag '{}' does not match any supported configuration; skipping this wheel as an install candidate. This usually means the wheel file was renamed with a malformed tag — fix the filename in the registry and re-lock.".format(wheel_name, python_tag))
    return kept

_PYTHON_VERSION_MAJOR_MINOR_FLAG = Label("@rules_python//python/config_settings:python_version_major_minor")
_ARPY_PYTHON_VERSION_FLAG = Label("@aspect_rules_py//py/private/interpreter:python_version")

def is_python_version_at_least(name, version = None, visibility = visibility, **kwargs):
    version = version or name
    flag_name = "_{}_flag".format(name)
    native.config_setting(
        name = name,
        flag_values = {
            flag_name: "yes",
        },
        visibility = visibility,
    )
    _python_version_at_least(
        name = flag_name,
        at_least = version,
        visibility = ["//visibility:private"],
        **kwargs
    )

def _python_version_at_least_impl(ctx):
    # Read from both sources
    rpy_value = ctx.attr._major_minor[config_common.FeatureFlagInfo].value
    arpy_raw = ctx.attr._arpy_version[BuildSettingInfo].value

    # Normalize aspect_rules_py flag to major.minor
    arpy_value = ""
    if arpy_raw:
        parts = arpy_raw.split(".")
        if len(parts) >= 2:
            arpy_value = "{}.{}".format(parts[0], parts[1])

    # Error on disagreement when both are set
    if arpy_value and rpy_value and arpy_value != rpy_value:
        fail(
            "Python version mismatch: " +
            "@aspect_rules_py//py/private/interpreter:python_version is {}, ".format(arpy_value) +
            "but @rules_python python_version_major_minor is {}. ".format(rpy_value) +
            "These must agree.",
        )

    # Aspect flag is authoritative; rules_python is fallback
    flag_value = arpy_value or rpy_value

    if not flag_value:
        return [config_common.FeatureFlagInfo(value = "no")]

    current = tuple([int(x) for x in flag_value.split(".")])
    at_least = tuple([int(x) for x in ctx.attr.at_least.split(".")])

    value = "yes" if current >= at_least else "no"
    return [config_common.FeatureFlagInfo(value = value)]

_python_version_at_least = rule(
    implementation = _python_version_at_least_impl,
    attrs = {
        "at_least": attr.string(mandatory = True),
        "_major_minor": attr.label(default = _PYTHON_VERSION_MAJOR_MINOR_FLAG),
        "_arpy_version": attr.label(default = _ARPY_PYTHON_VERSION_FLAG),
    },
)
