"""Repository rule that auto-detects an active $VIRTUAL_ENV and creates a Python toolchain from it.

When `$VIRTUAL_ENV` is set (i.e. the user has activated a virtualenv), this rule
probes the interpreter at `$VIRTUAL_ENV/bin/python3` and generates:

- A `rules_python`-compatible toolchain implementation (`:python_runtimes`)
- A `config_setting` (`:is_active`) that is satisfied when a venv was detected

When `$VIRTUAL_ENV` is not set or the interpreter cannot be probed, the rule
generates an incompatible toolchain that will never match, causing Bazel to
fall through to the next registered (hermetic) toolchain.

Because `environ = ["VIRTUAL_ENV"]` is declared, Bazel will automatically
refetch this repository whenever `$VIRTUAL_ENV` changes (e.g. on
`source .venv/bin/activate` or `deactivate`).

## Usage with bzlmod

```starlark
# MODULE.bazel
bazel_dep(name = "aspect_rules_py", version = "...")

venv_toolchain = use_repo_rule(
    "@aspect_rules_py//py/private/venv_toolchain:repository.bzl",
    "venv_toolchain",
)
venv_toolchain(name = "venv_python")

# Register the venv toolchain with higher priority than hermetic toolchains.
# It will only match when $VIRTUAL_ENV was set at repo-fetch time.
register_toolchains("@venv_python//:toolchains")
```

## Selectifying deps

The generated `@venv_python//:is_active` config_setting can be used in
`select()` to drop hermetic third-party deps when running under the venv
interpreter (since packages are already available in the venv's site-packages):

```starlark
# //build/defs.bzl
def my_py_test(name, deps = [], **kwargs):
    native.py_test(
        name = name,
        deps = select({
            "@venv_python//:is_active": [
                d for d in deps
                if not d.startswith("@pypi//")
            ],
            "//conditions:default": deps,
        }),
        **kwargs
    )
```
"""

load("@bazel_skylib//lib:paths.bzl", "paths")

# Template for the BUILD file when a venv IS detected.
# This creates the toolchain implementation targets and a config_setting
# gated on a bool_flag that defaults to True.
_ACTIVE_BUILD_TEMPLATE = """\
# Generated by @aspect_rules_py//py/private/venv_toolchain:repository.bzl
# VIRTUAL_ENV={venv_path}

load("@rules_python//python/private:local_runtime_repo_setup.bzl", "define_local_runtime_toolchain_impl")
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

define_local_runtime_toolchain_impl(
    name = "local_runtime",
    lib_ext = "{lib_ext}",
    major = "{major}",
    minor = "{minor}",
    micro = "{micro}",
    interpreter_path = "{interpreter_path}",
    implementation_name = "{implementation_name}",
    os = "{os}",
)

# Flag that records whether a venv was detected at repo-fetch time.
# Defaults to True here because this template is only used when VIRTUAL_ENV was set.
bool_flag(
    name = "_venv_detected",
    build_setting_default = True,
    visibility = ["//visibility:public"],
)

config_setting(
    name = "is_active",
    flag_values = {{":_venv_detected": "True"}},
    visibility = ["//visibility:public"],
)

# Toolchain registrations gated on is_active.
toolchain(
    name = "toolchains",
    toolchain = ":python_runtimes",
    toolchain_type = "@rules_python//python:toolchain_type",
    target_settings = [":is_active"],
    target_compatible_with = [":os"],
    visibility = ["//visibility:public"],
)
"""

# Template for the BUILD file when NO venv is detected.
# Creates a bool_flag defaulting to False and a config_setting that won't match,
# plus an incompatible toolchain so register_toolchains() doesn't error.
_INACTIVE_BUILD_TEMPLATE = """\
# Generated by @aspect_rules_py//py/private/venv_toolchain:repository.bzl
# No VIRTUAL_ENV detected.

load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

bool_flag(
    name = "_venv_detected",
    build_setting_default = False,
    visibility = ["//visibility:public"],
)

config_setting(
    name = "is_active",
    flag_values = {":_venv_detected": "True"},
    visibility = ["//visibility:public"],
)

# Placeholder filegroup so the toolchain() target below has something to point at.
filegroup(
    name = "python_runtimes",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchains",
    toolchain = ":python_runtimes",
    toolchain_type = "@rules_python//python:toolchain_type",
    target_settings = [":is_active"],
    target_compatible_with = ["@platforms//:incompatible"],
    visibility = ["//visibility:public"],
)
"""

_OS_MAP = {
    "linux": "linux",
    "mac os x": "macos",
    "windows": "windows",
}

def _venv_toolchain_impl(rctx):
    venv = rctx.os.environ.get("VIRTUAL_ENV")

    rctx.file("WORKSPACE", "")
    rctx.file("MODULE.bazel", "")

    if not venv:
        rctx.file("BUILD.bazel", _INACTIVE_BUILD_TEMPLATE)
        return

    interpreter = "{}/bin/python3".format(venv)
    if not rctx.path(interpreter).exists:
        # Might be Windows
        interpreter = "{}\\Scripts\\python.exe".format(venv)
        if not rctx.path(interpreter).exists:
            # buildifier: disable=print
            print("venv_toolchain: VIRTUAL_ENV={} set but interpreter not found, skipping".format(venv))
            rctx.file("BUILD.bazel", _INACTIVE_BUILD_TEMPLATE)
            return

    result = rctx.execute([
        interpreter,
        rctx.path(rctx.attr._probe_script),
    ])
    if result.return_code != 0:
        # buildifier: disable=print
        print("venv_toolchain: failed to probe interpreter at {}: {}".format(
            interpreter,
            result.stderr,
        ))
        rctx.file("BUILD.bazel", _INACTIVE_BUILD_TEMPLATE)
        return

    info = json.decode(result.stdout)

    # Symlink headers for cc interop
    include_path = rctx.path(info["include"])
    if include_path.exists:
        rctx.symlink(include_path, "include")

    # Symlink shared libraries
    shared_lib_names = [
        v
        for v in [
            info.get("PY3LIBRARY", ""),
            info.get("LDLIBRARY", ""),
            info.get("INSTSONAME", ""),
        ]
        if v
    ]
    shared_lib_dir = info.get("LIBDIR", "")
    for name in {v: None for v in shared_lib_names}.keys():
        origin = rctx.path("{}/{}".format(shared_lib_dir, name))
        if origin.exists:
            rctx.symlink(origin, "lib/" + name)

    os_name = _OS_MAP.get(rctx.os.name.lower(), rctx.os.name)

    rctx.file("BUILD.bazel", _ACTIVE_BUILD_TEMPLATE.format(
        venv_path = venv,
        major = info["major"],
        minor = info["minor"],
        micro = info["micro"],
        interpreter_path = interpreter,
        lib_ext = info.get("SHLIB_SUFFIX", ".so"),
        implementation_name = info.get("implementation_name", "cpython"),
        os = "@platforms//os:" + os_name,
    ))

venv_toolchain = repository_rule(
    implementation = _venv_toolchain_impl,
    doc = """Auto-detect an active virtualenv and create a Python toolchain from it.

See the module docstring for full usage instructions.
""",
    attrs = {
        "_probe_script": attr.label(
            allow_single_file = True,
            default = Label(":probe_interpreter.py"),
        ),
    },
    environ = ["VIRTUAL_ENV"],
)
