# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Commitizen runs in commit-msg stage
# but we don't want to run the other hooks on commit messages
default_stages: [commit]

repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 7.3.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            examples/django/mysite/settings.py|
            gazelle_python.yaml
          )

  - repo: local
    hooks:
      - id: check-docs
        name: Update docs
        entry: /usr/bin/env bazel run //docs:update
        language: script
        files: \.bzl$

  - repo: local
    hooks:
      - id: check-manifets
        name: Update gazelle manifest
        entry: /usr/bin/env bazel run //:gazelle_python_manifest.update
        language: script
        files: requirements.txt\$
