# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 7.3.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            examples/django/mysite/settings.py|
            gazelle_python.yaml
          )

  - repo: local
    hooks:
      - id: check-requirements-lock
        name: Update requirements lock
        # Note that we use a nested shell to discard $@, which is the file list
        entry: /bin/sh -c '/usr/bin/env bazel run //:requirements.update'
        language: script
        require_serial: true

      - id: check-gazelle-manifest
        name: Update gazelle manifest
        # Note that we use a nested shell to discard $@, which is the file list
        entry: /bin/sh -c '/usr/bin/env bazel run //:gazelle_python_manifest.update'
        language: script
        require_serial: true

      - id: check-amd64-image-lists
        name: Update amd64 image lists
        # Note that we use a nested shell to discard $@, which is the file list
        entry: /bin/sh -c '/usr/bin/env bazel run //py/tests/py_venv_image_layer:my_app_amd64_layers'
        language: script
        require_serial: true

      - id: check-arm64-image-lists
        name: Update arm64 image lists
        # Note that we use a nested shell to discard $@, which is the file list
        entry: /bin/sh -c '/usr/bin/env bazel run //py/tests/py_venv_image_layer:my_app_arm64_layers'
        language: script
        require_serial: true
