load("//py:defs.bzl", "py_test")

exports_files(
    ["site_merge.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "site_merge_test",
    srcs = [
        "site_merge.py",
        "site_merge_test.py",
    ],
    data = ["//py/tools/unpack:exclude_glob_test_vectors.bzl"],
    imports = ["."],
    main = "site_merge_test.py",
)
