"""Site-packages subtree merger for aspect_rules_py venv assembly.

Physically merges one package directory contributed by multiple wheels
into a single output directory — the shape a flat `pip install` into one
site-packages would produce.

Needed when a *regular* package (one with an `__init__.py`) spans
wheels: e.g. azure-core owns `azure/core/` while
azure-core-tracing-opentelemetry installs
`azure/core/tracing/ext/opentelemetry_span/` into that same tree.
Python locks a regular package's `__path__` to the first directory
found on `sys.path`, so unlike PEP 420 namespace portions the
contributions cannot be merged at import time — they have to be merged
on disk.

Invoked by Bazel as::

    <exec_python> site_merge.py --into <dir> [--collision-policy P] --src <dir> [--src <dir> ...]

Each ``--src`` is one wheel's copy of the package directory, in overlay
order: on conflicts the later wheel overlays the earlier one. Sources
that don't exist are skipped (platform wheels for other architectures
may not ship the directory).
"""

import argparse
import ast
import filecmp
import os
import shutil
import stat
import sys
from pathlib import Path


def _is_namespace_init_ast(tree):
    """Return True if the AST is a recognized namespace package declaration.

    Accepts the canonical forms generated by setuptools/pkgutil namespace
    packages. Any executable code beyond the namespace declaration returns
    False so that real collisions are still surfaced.
    """
    # Unwrap a Module body.
    body = tree.body if isinstance(tree, ast.Module) else [tree]

    # Drop any docstring/Expr(Str) statements that may appear in legacy stubs.
    meaningful = []
    import_seen = False
    for stmt in body:
        if (
            isinstance(stmt, ast.Expr) and
            isinstance(stmt.value, ast.Constant) and
            isinstance(stmt.value.value, str)
        ):
            continue
        # Track the canonical `from pkgutil import extend_path` import, then
        # expect the assignment as the only other meaningful statement.
        if isinstance(stmt, ast.ImportFrom) and stmt.module == "pkgutil":
            if len(stmt.names) == 1 and stmt.names[0].name == "extend_path":
                import_seen = True
                continue
        meaningful.append(stmt)

    if len(meaningful) != 1:
        return False
    stmt = meaningful[0]

    # pkgutil form 1: __path__ = __import__("pkgutil").extend_path(__path__, __name__)
    if isinstance(stmt, ast.Assign):
        if len(stmt.targets) != 1:
            return False
        target = stmt.targets[0]
        if not (isinstance(target, ast.Name) and target.id == "__path__"):
            return False
        return _is_pkgutil_extend_path_call(stmt.value)

    # pkg_resources form: __import__("pkg_resources").declare_namespace(__name__)
    if isinstance(stmt, ast.Expr):
        return _is_pkg_resources_declare_namespace_call(stmt.value)

    # try/except fallback form:
    # try:
    #     __import__("pkg_resources").declare_namespace(__name__)
    # except ImportError:
    #     __import__("pkgutil").extend_path(__path__, __name__)
    if isinstance(stmt, ast.Try):
        if len(stmt.body) != 1 or len(stmt.handlers) != 1:
            return False
        if not (
            stmt.handlers[0].type is None and
            len(stmt.handlers[0].body) == 1
        ):
            return False
        return (
            _is_pkg_resources_declare_namespace_call(stmt.body[0].value) and
            _is_pkgutil_extend_path_call(stmt.handlers[0].body[0].value)
        )

    return False


def _is_pkgutil_extend_path_call(node):
    """Return True if node is pkgutil.extend_path(__path__, __name__) or equivalent."""
    if not isinstance(node, ast.Call):
        return False
    func = node.func

    # pkgutil form 2 (module attribute): import pkgutil;
    # __path__ = pkgutil.extend_path(__path__, __name__)
    if (
        isinstance(func, ast.Attribute) and
        func.attr == "extend_path" and
        isinstance(func.value, ast.Name) and
        func.value.id == "pkgutil"
    ):
        return _is_extend_path_args(node.args)

    # pkgutil form 3 (name-loaded call): from pkgutil import extend_path;
    # __path__ = extend_path(__path__, __name__)
    if (
        isinstance(func, ast.Name) and
        func.id == "extend_path"
    ):
        return _is_extend_path_args(node.args)

    # __import__("pkgutil").extend_path
    if (
        isinstance(func, ast.Attribute) and
        func.attr == "extend_path" and
        isinstance(func.value, ast.Call)
    ):
        call = func.value
        if (
            isinstance(call.func, ast.Name) and
            call.func.id == "__import__" and
            len(call.args) == 1 and
            isinstance(call.args[0], ast.Constant) and
            call.args[0].value == "pkgutil"
        ):
            return _is_extend_path_args(node.args)

    return False


def _is_extend_path_args(args):
    """Return True if args are (__path__, __name__)."""
    if len(args) != 2:
        return False
    return (
        isinstance(args[0], ast.Name) and args[0].id == "__path__" and
        isinstance(args[1], ast.Name) and args[1].id == "__name__"
    )


def _is_pkg_resources_declare_namespace_call(node):
    """Return True if node is pkg_resources.declare_namespace(__name__) or equivalent."""
    if not isinstance(node, ast.Call):
        return False
    func = node.func

    # pkg_resources.declare_namespace
    if (
        isinstance(func, ast.Attribute) and
        func.attr == "declare_namespace" and
        isinstance(func.value, ast.Name) and
        func.value.id == "pkg_resources"
    ):
        return _is_declare_namespace_args(node.args)

    # __import__("pkg_resources").declare_namespace
    if (
        isinstance(func, ast.Attribute) and
        func.attr == "declare_namespace" and
        isinstance(func.value, ast.Call)
    ):
        call = func.value
        if (
            isinstance(call.func, ast.Name) and
            call.func.id == "__import__" and
            len(call.args) == 1 and
            isinstance(call.args[0], ast.Constant) and
            call.args[0].value == "pkg_resources"
        ):
            return _is_declare_namespace_args(node.args)

    return False


def _is_declare_namespace_args(args):
    """Return True if args are (__name__,)."""
    return (
        len(args) == 1 and
        isinstance(args[0], ast.Name) and
        args[0].id == "__name__"
    )


def _is_namespace_init_stub(content):
    """Return True if the __init__.py content is a namespace package stub."""
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return False
    return _is_namespace_init_ast(tree)


def _are_files_equivalent(src_file, dest):
    """Compare two files, treating namespace stubs as equivalent.

    Returns True if the files are byte-identical or if both are
    __init__.py files containing only a recognized namespace package stub.
    """
    if filecmp.cmp(str(src_file), str(dest), shallow=False):
        return True
    if src_file.name != "__init__.py" or dest.name != "__init__.py":
        return False
    src_content = src_file.read_text()
    dest_content = dest.read_text()
    return (
        _is_namespace_init_stub(src_content) and
        _is_namespace_init_stub(dest_content)
    )


def _remove(path):
    """Remove an output copied from a potentially read-only input."""

    def retry_readonly(function, candidate, exc_info):
        error = exc_info[1]
        if not isinstance(error, PermissionError):
            raise error
        candidate = Path(candidate)
        candidate.chmod(candidate.stat().st_mode | stat.S_IWRITE)
        function(candidate)

    if path.is_dir():
        shutil.rmtree(path, onerror=retry_readonly)
        return
    try:
        path.unlink()
    except PermissionError:
        path.chmod(path.stat().st_mode | stat.S_IWRITE)
        path.unlink()


def merge(into, sources):
    into.mkdir(parents=True, exist_ok=True)
    owners = {}
    conflicts = []

    for src in sources:
        if not src.is_dir():
            continue
        for root, dirs, files in os.walk(src):
            dirs.sort()
            files.sort()
            rel_root = Path(root).relative_to(src)
            for d in dirs:
                rel = rel_root / d
                dest_dir = into / rel_root / d
                if dest_dir.exists() and not dest_dir.is_dir():
                    conflicts.append((rel, owners.get(rel), src))
                    _remove(dest_dir)
                dest_dir.mkdir(parents=True, exist_ok=True)
                owners[rel] = src
            for f in files:
                rel = rel_root / f
                dest = into / rel
                src_file = Path(root) / f
                if dest.is_dir():
                    conflicts.append((rel, owners.get(rel), src))
                    _remove(dest)
                prior = owners.get(rel)
                if dest.exists():
                    # The wheel extractor treats any execute bit as executable
                    # (py/tools/unpack/unpack.py). Other mode differences may
                    # reflect executor umask and are benign for identical data.
                    if _are_files_equivalent(src_file, dest):
                        src_executable = bool(src_file.stat().st_mode & 0o111)
                        dest_executable = bool(dest.stat().st_mode & 0o111)
                        if src_executable != dest_executable:
                            conflicts.append((rel, prior, src))
                        shutil.copymode(str(src_file), str(dest))
                        owners[rel] = src
                        continue
                    conflicts.append((rel, prior, src))
                    _remove(dest)
                shutil.copy(str(src_file), str(dest))
                owners[rel] = src

    return conflicts


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--into", required=True, type=Path)
    ap.add_argument("--src", dest="sources", action="append", default=[], type=Path)
    ap.add_argument(
        "--collision-policy",
        default="warning",
        choices=["error", "warning", "ignore"],
    )
    args = ap.parse_args()

    conflicts = merge(args.into, args.sources)

    if conflicts and args.collision_policy != "ignore":
        for rel, previous, current in conflicts:
            print(
                "Package collision while merging {}: `{}` is provided by both {} and {}.".format(
                    args.into, rel, previous, current
                ),
                file=sys.stderr,
            )
        if args.collision_policy == "error":
            raise SystemExit(
                'Set `package_collisions = "warning"` or "ignore" to downgrade.'
            )


if __name__ == "__main__":
    main()
