"""Repository rule generating the surface hub that exposes uv-resolved dependencies to the build."""

load("//uv/private/pprint:defs.bzl", "indent", "pprint")

def _dep_group_config_setting(name):
    """Renders a config_setting block matching one configuration name against the dep_group flag."""
    return "\n".join([
        "config_setting(",
        '    name = "%s",' % name,
        "    flag_values = {",
        '        "@aspect_rules_py//uv/private/constraints/dep_group:dep_group": "%s",' % name,
        "    },",
        '    visibility = ["//visibility:public"],',
        ")",
    ])

def _pkg_alias(name):
    """Renders the :pkg convenience alias, trailing newline included for inline splicing."""
    return "\n".join([
        "alias(",
        '    name = "pkg",',
        '    actual = "%s",' % name,
        '    visibility = ["//visibility:public"],',
        ")",
        "",
    ])

def _hub_impl(repository_ctx):
    """Generates the surface hub repository exposing resolved dependencies.

    The hub performs no resolution of its own: every alias forwards into a
    per-project repository (generated by `uv_project`) that owns the resolved
    graph for one configuration. Five artifacts are laid down:

    - `dep_group/BUILD.bazel`: a `dep_group` alias over the universal
      `string_flag` plus one `config_setting` per configuration name. Every
      other artifact's `select()` keys off these settings, so this file is
      generated first.
    - `BUILD.bazel`: a `gazelle_index_whls` filegroup selecting the active
      project's wheel index for Gazelle, plus the `exports_files` declaration
      for the two loadable files below.
    - `<package>/BUILD.bzl`: one directory per package exposing `:{name}`,
      `:whl`, and `:pkg` aliases whose `select()` arms point at the project
      repo providing that package under each configuration. The aliases carry
      `target_compatible_with = select(compatible_with(...))` so packages
      missing from the active group are skipped instead of failing analysis,
      while `no_match_error` covers the unset-group case. A distribution
      literally named "pkg" suppresses the `:pkg` alias, which would collide
      with its own `:{name}` target.
    - `defs.bzl`: the rules_py-native API (`VIRTUALENVS`, `compatible_with`/
      `incompatible_with`, `group_deps()`, `group_deps_for()`). The group
      table inverts the sparse `{package: {group: target}}` mapping into
      `group -> [canonical :pkg labels]` in a single pass over the sorted
      package names, seeding every known group so an empty group still yields
      an empty select arm. Select keys in the emitted file are wrapped in
      `Label(...)` so they resolve against this hub repository rather than
      whichever package ends up loading the file.
    - `requirements.bzl`: a rules_python-compatibility shim (`requirement()`,
      `all_requirements`, and friends). Its surface must stay aligned with
      rules_python's generated `requirements.bzl`; rules_py-specific additions
      belong in `defs.bzl`.

    Console-script entry points are not yet exposed.

    Args:
        repository_ctx: `attr.packages` carries a JSON blob shaped
            `{requirement: {configuration: target}}`; `attr.configurations`
            maps each configuration name to the project repository containing
            it.

    Returns:
        Reproducible repository metadata: generation is a pure function of the
        rule attributes, with no network or environment access.
    """

    packages = json.decode(repository_ctx.attr.packages)
    package_names = sorted(packages.keys())

    repository_ctx.template(
        "dep_group/BUILD.bazel",
        repository_ctx.attr._dep_group_build_template,
        substitutions = {
            "%CONFIG_SETTINGS%": "\n\n\n".join([
                _dep_group_config_setting(name)
                for name in repository_ctx.attr.configurations
            ]),
        },
    )

    index_select_clauses = {
        "//dep_group:%s" % cfg: ["@%s//:gazelle_index_whls" % project_id]
        for cfg, project_id in repository_ctx.attr.configurations.items()
    }

    repository_ctx.template(
        "BUILD.bazel",
        repository_ctx.attr._root_build_template,
        substitutions = {
            "%INDEX_SELECT_CLAUSES%": indent(pprint(index_select_clauses), "        ").lstrip(),
        },
    )

    for package_name, specs in packages.items():
        select_spec = {
            "//dep_group:%s" % cfg: label
            for cfg, label in specs.items()
        }
        whl_select_spec = {
            "//dep_group:%s" % cfg: label + "_whl"
            for cfg, label in specs.items()
        }

        error = "Available only in dep_groups: " + ", ".join(specs.keys())

        pkg_alias = "" if package_name == "pkg" else _pkg_alias(package_name)

        repository_ctx.template(
            package_name + "/BUILD.bazel",
            repository_ctx.attr._package_build_template,
            substitutions = {
                "%PKG_ALIAS%": pkg_alias,
                "%WHL_SELECT%": indent(pprint(whl_select_spec), "      ").lstrip(),
                "%NAME%": package_name,
                "%LIB_SELECT%": indent(pprint(select_spec), "      ").lstrip(),
                "%COMPAT%": repr(specs.keys()),
                "%ERROR%": error,
            },
        )

    deps_by_group = {group: [] for group in sorted(repository_ctx.attr.configurations)}
    for name in package_names:
        label = "@@%s//%s:pkg" % (repository_ctx.name, name)
        for group in packages[name]:
            if group in deps_by_group:
                deps_by_group[group].append(label)

    repository_ctx.template(
        "defs.bzl",
        repository_ctx.attr._defs_template,
        substitutions = {
            "%VIRTUALENVS%": pprint(repository_ctx.attr.configurations.keys()),
            "%DEPS_BY_GROUP%": pprint(deps_by_group),
            "%NO_MATCH_ERROR%": repr(
                "no dep_group selected; set the dep_group attribute on the consuming target to one of: " +
                ", ".join(sorted(repository_ctx.attr.configurations)),
            ),
        },
    )

    repository_ctx.template(
        "requirements.bzl",
        repository_ctx.attr._requirements_template,
        substitutions = {
            "%ALL_REQUIREMENTS%": repr([
                "@@%s//%s:pkg" % (repository_ctx.name, name)
                for name in package_names
            ]),
            "%ALL_WHL_REQUIREMENTS_BY_PACKAGE%": repr({
                name: "@@%s//%s:whl" % (repository_ctx.name, name)
                for name in package_names
            }),
            "%REPO_NAME%": repository_ctx.name,
        },
    )

    return repository_ctx.repo_metadata(reproducible = True)

uv_hub = repository_rule(
    doc = """
    Generates the surface hub repository exposed to the build.

    Five artifacts are laid down:

    - `dep_group/BUILD.bazel`: a `dep_group` alias over the universal
      `string_flag` plus one `config_setting` per configuration name.
    - `BUILD.bazel`: a `gazelle_index_whls` filegroup selecting the active
      project's wheel index for Gazelle.
    - `<package>/BUILD.bzl`: public `:{name}`, `:whl`, and `:pkg` aliases for
      every package, resolving through `select()` to the project repo
      providing it under each configuration.
    - `defs.bzl` (rules_py-native): the `group_deps()` and `group_deps_for()`
      helpers plus the `compatible_with` / `incompatible_with` constraint
      helpers and the `VIRTUALENVS` list.
    - `requirements.bzl`: a rules_python-compatibility shim (`all_requirements`,
      `requirement()`, and friends).

    `group_deps()` returns the dependency list for whichever dependency group
    the consuming target selects via its `dep_group` attribute. A hub spanning
    multiple projects has an `all_requirements` union whose members are
    incompatible under any single `dep_group`; `group_deps()` resolves instead
    to just the subset valid for the active group. Because `dep_group` drives an
    incoming transition, the returned `select()` is evaluated under the chosen
    group, so it is used directly without repeating the group name:

        deps = group_deps()

    It is a function rather than a value so that future options -- such as
    PEP 508 package extras -- can be added as keyword arguments without breaking
    callers.

    `group_deps_for(name)` returns the membership of one explicit group as
    sorted `Label` values, for macros that must inspect package names (via
    `Label.package`) during package loading or deliberately pin one group's
    deps. The aliases still resolve under the active `dep_group`, so a consuming
    target that uses these labels as `deps` must set the matching group itself.
    It is the only public accessor for the per-group membership; the underlying
    table is built once at load and shared with the `group_deps()` select.
    """,
    implementation = _hub_impl,
    attrs = {
        "configurations": attr.string_dict(
            doc = """
            Maps a configuration name to the repository name of the project
            containing that configuration. The keys become the emitted
            `config_setting` names, the `VIRTUALENVS` list, and the select
            arms of every generated alias.
            """,
        ),
        "packages": attr.string(
            doc = """
            JSON blob shaped `{package: {configuration: label}}`, where each
            label points at the package's target inside the providing project
            repository. JSON-encoded because the two-level nesting cannot be
            expressed as a native attr type.
            """,
        ),
        "_dep_group_build_template": attr.label(
            doc = "Skeleton for the generated `dep_group/BUILD.bazel`.",
            allow_single_file = True,
            default = Label("//uv/private/uv_hub/templates:dep_group_build.tmpl"),
        ),
        "_root_build_template": attr.label(
            doc = "Skeleton for the generated root `BUILD.bazel`.",
            allow_single_file = True,
            default = Label("//uv/private/uv_hub/templates:root_build.tmpl"),
        ),
        "_package_build_template": attr.label(
            doc = "Skeleton for each generated `<package>/BUILD.bazel`.",
            allow_single_file = True,
            default = Label("//uv/private/uv_hub/templates:package_build.tmpl"),
        ),
        "_defs_template": attr.label(
            doc = "Skeleton for the generated `defs.bzl`.",
            allow_single_file = True,
            default = Label("//uv/private/uv_hub/templates:defs.tmpl"),
        ),
        "_requirements_template": attr.label(
            doc = "Skeleton for the generated `requirements.bzl`.",
            allow_single_file = True,
            default = Label("//uv/private/uv_hub/templates:requirements.tmpl"),
        ),
    },
)
