
load("@aspect_rules_py//uv/private/pep517_whl:pep517_whl.bzl", "pep517_whl")
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py"],
    deps = ["@@+uv+project__aspect_rules_py//:build", "@@+uv+project__aspect_rules_py//:setuptools", "@@+uv+project__aspect_rules_py//:maturin", "@project__aspect_rules_py//private/build_deps:setuptools"],
    include_console_scripts = True,
)

pep517_whl(
    name = "whl",
    src = "@@+uv+sdist__bravado_core__8cf1f7bbac2f7c69//file:file",
    tool = ":build_tool",
    version = "6.1.1",
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
