
load("@aspect_rules_py//uv/private/pep517_whl:rule.bzl", "pep517_whl")
load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@aspect_rules_py//uv/private/markers:defs.bzl", "decide_marker")

decide_marker(
    name = "_build_dep_marker_0",
    marker = "os_name == 'nt'",
)

decide_marker(
    name = "_build_dep_marker_1",
    marker = "python_full_version < '3.10.2'",
)

decide_marker(
    name = "_build_dep_marker_2",
    marker = "python_full_version < '3.11'",
)

decide_marker(
    name = "_build_dep_marker_3",
    marker = "(python_full_version < '3.10.2') and (python_full_version < '3.11')",
)

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl:build_helper.py"],
    deps = ["@@+uv+whl_install__aspect_rules_py__build__1_3_0//:install", "@@+uv+whl_install__aspect_rules_py__setuptools__80_9_0//:install", "@@+uv+whl_install__aspect_rules_py__maturin__1_11_5//:install", "@@+uv+whl_install__aspect_rules_py__packaging__24_0//:install", "@@+uv+whl_install__aspect_rules_py__pyproject_hooks__1_2_0//:install"] + select({
        ":_build_dep_marker_0": ["@@+uv+whl_install__aspect_rules_py__colorama__0_4_6//:install"],
        "//conditions:default": [],
    }) + select({
        ":_build_dep_marker_1": ["@@+uv+whl_install__aspect_rules_py__importlib_metadata__8_7_1//:install"],
        "//conditions:default": [],
    }) + select({
        ":_build_dep_marker_2": ["@@+uv+whl_install__aspect_rules_py__tomli__2_4_0//:install"],
        "//conditions:default": [],
    }) + select({
        ":_build_dep_marker_3": ["@@+uv+whl_install__aspect_rules_py__zipp__3_23_0//:install"],
        "//conditions:default": [],
    }),
)

pep517_whl(
    name = "whl",
    src = "@@+uv+sdist__bravado_core__8cf1f7bbac2f7c69//file:file",
    tool = ":build_tool",
    version = "6.1.1",
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
