"""
Helpers & constants.

The ABI tag allowlist defined here is the single source of truth used by both
supported_abi() (to filter wheel tags) and generate() in macro.bzl (to create
the config_setting_group targets). Keeping both sides derived from the same
data makes "unsupported tag passes the filter but has no target" bugs
impossible by construction.
"""

load("//uv/private/constraints:defs.bzl", "INTERPRETERS", "MAJORS", "MINORS", "foreign_interpreter_tag")

# Interpreter feature flag letters in canonical abi tag order, mapped to the
# names of the enabled/disabled config_settings generated in macro.bzl.
ABI_FEATURES = {
    "d": "pydebug",
    "m": "pymalloc",
    "t": "freethreading",
    "u": "wide_unicode",
}

def _generate_feature_suffixes():
    suffixes = [""]
    for feature in ABI_FEATURES.keys():
        suffixes = suffixes + [suffix + feature for suffix in suffixes]
    return suffixes

# Every combination of feature letters in canonical order, "" included.
ABI_FEATURE_SUFFIXES = _generate_feature_suffixes()

def _generate_abi_tags():
    tags = {
        "none": True,
        "abi3": True,
    }
    for interpreter in INTERPRETERS:
        for major in MAJORS:
            for minor in MINORS:
                for suffix in ABI_FEATURE_SUFFIXES:
                    tags["{}{}{}{}".format(interpreter, major, minor, suffix)] = True
    return tags

ABI_TAGS = _generate_abi_tags()

def supported_abi(abi_tag):
    """Predicate.

    Indicate whether a wheel abi tag has a corresponding config_setting_group
    target generated by macro.bzl. Allows for filtering out of wheels for
    foreign interpreter ABIs (e.g. pypy310_pp73) as well as malformed tags
    (e.g. `cp311_2` from a renamed wheel file) which would otherwise become
    select conditions on nonexistent targets.

    Args:
        abi_tag (str): A wheel abi tag

    Returns:
        bool; whether the abi is supported and can be configured or not.

    """
    return abi_tag in ABI_TAGS

def filter_abi_tags(wheel_name, abi_tags):
    """Filter a wheel's abi tags down to the supported allowlist.

    Tags for known foreign interpreters are dropped silently; anything else
    unsupported is dropped with a warning since it usually indicates a
    malformed (e.g. renamed) wheel filename.

    Args:
        wheel_name (str): The wheel filename, for diagnostics.
        abi_tags (list of str): Parsed abi tags of that wheel.

    Returns:
        list of str; the supported abi tags in their original order.
    """
    kept = []
    for abi_tag in abi_tags:
        if supported_abi(abi_tag):
            kept.append(abi_tag)
        elif not foreign_interpreter_tag(abi_tag):
            # buildifier: disable=print
            print("WARNING: {}: abi tag '{}' does not match any supported configuration; skipping this wheel as an install candidate. This usually means the wheel file was renamed with a malformed tag — fix the filename in the registry and re-lock.".format(wheel_name, abi_tag))
    return kept
