# Collected constraints from PyPi wheels
load("@bazel_skylib//lib:selects.bzl", "selects")

## These are defined but we're ignoring them for now.
# android_21_arm64_v8a
# android_21_armeabi_v7a
# android_21_x86_64
# android_24_arm64_v8a
# android_24_x86_64
# android_26_arm64_v8a
# android_26_x86_64
# android_28_arm64_v8a
# android_33_arm64_v8a
# ios_13_0_arm64_iphoneos
# ios_13_0_arm64_iphonesimulator
# ios_13_0_x86_64_iphonesimulator

## These are long obsolete manylinux wheel formats we're ignoring.
## Hopefully we can just ignore that....
# manylinux1_i686
# manylinux1_x86_64
# manylinux2010_i686
# manylinux2010_x86_64
# manylinux2014_aarch64
# manylinux2014_armv7l
# manylinux2014_i686
# manylinux2014_ppc64
# manylinux2014_ppc64le
# manylinux2014_s390x
# manylinux2014_x86_64

## These seem wrong
# linux_armv6l
# linux_armv7l
# linux_x86_64
# macosx

def generate_gte_ladder(stages):
    """
    Accept a list of names of individual conditions representing specific versions.
    These names happen to be in ascending order and are generated by some other codepath.

    Given these conditon lable names generate a sequence ("ladder") of equality
    comparison operations + or with the "greater" comparison.

    So for [macos_10_0, macos_10_1, macos_11_0, macos_11_1, ...]
    We want to get

        selects.config_setting_group(
            name = "gte_macos_10_0",
            match_any = [
               ":macos_10_0",
               ":gte_macos_10_1",
            ],
        )
        selects.config_setting_group(
            name = "gte_macos_10_1",
            match_any = [
               ":macos_10_1",
               ":gte_macos_11_0",
            ],
        )

    and soforth. The trick is that we need one _fewer_ gte test than we have
    versions since we can't actually build out unbounded ranges in Bazel.

    """

    # We loop up to the second-to-last item to ensure we always have a 'next' stage.
    for i in range(len(stages) - 1):
        current_stage = stages[i]
        next_stage = stages[i+1]

        selects.config_setting_group(
            name = "{}".format(current_stage.name),
            match_any = [
                ":{}".format(current_stage.condition),
                ":{}".format(next_stage.name),
            ],
        )

    # And we do the last stage by hand.
    selects.config_setting_group(
        name = "{}".format(stages[-1].name),
        match_any = [
            ":{}".format(stages[-1].condition),
        ],
    )


def generate_macos():
    """
    Deliberately generate an overfull matrix of possible MacOS versions and arches.
    """

    # https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#macos
    arch_groups = {
        "universal2": ["arm64", "x86_64"],
        "universal": ["i386", "ppc", "ppc64", "x86_64"],
        "intel": ["i386", "x86_64"],
        "fat": ["i386", "ppc"],
        "fat3": ["i386", "ppc", "x86_64"],
        "fat64": ["ppc64", "x86_64"],
    }
    arches = [
        "arm64",
        "x86_64",
        "i386",
        "ppc",
        "ppc64",
    ]
    platform_repo_name_mangling = {
        "ppc64": "ppc64le"
    }

    stages = []

    # MacOS 10 ran for 15 minor releases
    # Since then with MacOS 11 (2020) Apple's gone to an annual major version
    # With MacOS 26 "Tahoe" they've gone to using the gregorian year for the version
    # Go a bit out into the future there
    for major in range(10, ):
        for minor in range(0, 20):
            name = "is_macos_{}_{}".format(major, minor)
            native.constraint_value(
                name = name,
                constraint_setting = ":platform",
            )
            stages.append(struct(name=name[3:], condition=name))

            for arch in arches:
                selects.config_setting_group(
                    name = "macos_{}_{}_{}".format(major, minor, arch),
                    match_all = [
                        ":macos_{}_{}".format(major, minor),
                        "@platforms//cpu:{}".format(platform_repo_name_mangling.get(arch, arch)),
                    ]
                )

            for group, members in arch_groups.items():
                selects.config_setting_group(
                    name = "macos_{}_{}_{}".format(major, minor, group),
                    match_any = [
                        ":macos_{}_{}_{}".format(major, minor, it)
                        for it in members
                    ]
                )

    generate_gte_ladder(stages)

    return stages


def generate_manylinux():
    # https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#manylinux

    arches = [
        "x86_64",
        "i686",
        "aarch64",
        "ppc64",
        "ppc64le",
        "s390x",
        "riscv64",
        "armv7l",
    ]
    platform_repo_name_mangling = {
        "armv7l": "armv7"
    }

    stages = []

    # glibc 1.X ran for not that long and was in the 90s
    for major in [2]:
        for minor in range(0, 51):
            name = "is_manylinux_{}_{}".format(major, minor)
            native.constraint_value(
                name = name,
                constraint_setting = ":platform",
            )
            stages.append(struct(name=name[3:], condition=name))

            for arch in arches:
                selects.config_setting_group(
                    name = "manylinux_{}_{}_{}".format(major, minor, arch),
                    match_all = [
                        ":manylinux_{}_{}".format(major, minor),
                        "@platforms//cpu:{}".format(platform_repo_name_mangling.get(arch, arch)),
                    ]
                )

    generate_gte_ladder(stages)

def generate_musllinux():
    arches = [
        "x86_64",
        "i686",
        "aarch64",
        "ppc64",
        "ppc64le",
        "s390x",
        "riscv64",
        "armv7l",
    ]
    platform_repo_name_mangling = {
        "armv7l": "armv7"
    }

    stages = []

    # TODO: musl moves super slow and has strong back compat promises, doesn't clearly need a huge matrix?
    for major, minor in [
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],  # Hypothetical
        [2, 2],  # Hypothetical
    ]:
        name = "is_musllinux_{}_{}".format(major, minor)
        native.constraint_value(
            name = name,
            constraint_setting = ":platform",
        )
        stages.append(struct(name=name[3:], condition=name))

        for arch in arches:
            selects.config_setting_group(
                name = "musllinux_{}_{}_{}".format(major, minor, arch),
                match_all = [
                    ":musllinux_{}_{}".format(major, minor),
                    "@platforms//cpu:{}".format(platform_repo_name_mangling.get(arch, arch)),
                ]
            )

    generate_gte_ladder(stages)

# musllinux_1_0_aarch64
# musllinux_1_0_armv7l
# musllinux_1_0_i686
# musllinux_1_0_x86_64
# musllinux_1_1_aarch64
# musllinux_1_1_armv7l
# musllinux_1_1_i686
# musllinux_1_1_ppc64le
# musllinux_1_1_riscv64
# musllinux_1_1_s390x
# musllinux_1_1_x86_64
# musllinux_1_2_aarch64
# musllinux_1_2_armv7l
# musllinux_1_2_i686
# musllinux_1_2_ppc64le
# musllinux_1_2_riscv64
# musllinux_1_2_s390x
# musllinux_1_2_x86_64
# musllinux_2_0_aarch64
# musllinux_2_0_x86_64

# win32
# win64
# win_amd64
# win_arm64
# win_ia64

def generate():
    # FIXME: Is there a better/worse way to do this?
    native.alias(
        name = "none",
        actual = "//conditions:default",
    )

    native.constraint_setting(
        name = "platform",
    )

    generate_macos()
    generate_manylinux()
    generate_musllinux()
