
load("@aspect_rules_py//uv/private/pep517_whl:rule.bzl", "pep517_native_whl")
load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@aspect_rules_py//uv/private/markers:defs.bzl", "decide_marker")

decide_marker(
    name = "_build_dep_marker_0",
    marker = "os_name == 'nt'",
)

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl:build_helper.py"],
    deps = ["@@aspect_rules_py++uv+whl_install__uv_sdist_native_build__build__1_4_0//:install", "@@aspect_rules_py++uv+whl_install__uv_sdist_native_build__setuptools__75_8_2//:install", "@@aspect_rules_py++uv+whl_install__uv_sdist_native_build__packaging__26_0//:install", "@@aspect_rules_py++uv+whl_install__uv_sdist_native_build__pyproject_hooks__1_2_0//:install"] + select({
        ":_build_dep_marker_0": ["@@aspect_rules_py++uv+whl_install__uv_sdist_native_build__colorama__0_4_6//:install"],
        "//conditions:default": [],
    }),
)

pep517_native_whl(
    name = "whl",
    src = "@@aspect_rules_py++uv+sdist__python_geohash__05a21fcf4eda1a5e//file:file",
    tool = ":build_tool",
    version = "0.8.5",
    resource_set = "mem_4g",
    pre_build_patches = ["@@//uv-sdist-native-build:require_cxx_driver.patch"],
    pre_build_patch_strip = 1,
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
