
load("@aspect_rules_py//uv/private/pep517_whl:pep517_native_whl.bzl", "pep517_native_whl")
load("@aspect_rules_py//uv/private/pep517_whl:frontend.bzl", "pep517_frontend")
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py"],
    deps = ["@@aspect_rules_py++uv+project__uv_sdist_native_build//:build", "@@aspect_rules_py++uv+project__uv_sdist_native_build//:setuptools", "@project__uv_sdist_native_build//private/build_deps:setuptools"],
    include_console_scripts = True,
)

pep517_frontend(
    name = "frontend",
    actual = ":build_tool",
)

pep517_native_whl(
    name = "whl",
    src = "@@aspect_rules_py++uv+sdist__python_geohash__05a21fcf4eda1a5e//file:file",
    tool = ":frontend",
    version = "0.8.5",
    resource_set = "mem_4g",
    pre_build_patches = ["@@//uv-sdist-native-build:require_cxx_driver.patch"],
    pre_build_patch_strip = 1,
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
