
load("@aspect_rules_py//uv/private/pep517_whl:pep517_native_whl.bzl", "pep517_native_whl")
load("@aspect_rules_py//uv/private/pep517_whl:frontend.bzl", "pep517_frontend")
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "build_tool",
    main = "@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py",
    srcs = ["@aspect_rules_py//uv/private/pep517_whl/tools:build_helper.py"],
    deps = ["@aspect_rules_py//uv/private/pep517_whl/tools:tools", "@@aspect_rules_py++uv+project__uv_sdist_fallback//:packaging", "@@aspect_rules_py++uv+project__uv_sdist_fallback//:build", "@@aspect_rules_py++uv+project__uv_sdist_fallback//:setuptools", "@project__uv_sdist_fallback//private/build_deps:setuptools"],
)

pep517_frontend(
    name = "frontend",
    actual = ":build_tool",
)

pep517_native_whl(
    name = "whl",
    src = "@@aspect_rules_py++uv+sdist__cowsay__47445cb273684618//file:file",
    tool = ":frontend",
    version = "6.0",
    console_scripts = ["cowsay=cowsay.__main__:cli"],
    monitor_memory = True,
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
