load("@aspect_rules_py//uv/private/whl_install:rule.bzl", "whl_dist")

whl_dist(
    name = "whl",
    src = "googleapis_common_protos-1.74.0-py3-none-any.whl",
    top_levels = [
        "google",
        "googleapis_common_protos-1.74.0.dist-info",
    ],
    top_level_dirs = [
        "google",
    ],
    namespace_top_levels = [
        "google",
    ],
    namespace_entries = [
        "google/api/annotations_pb2.py",
        "google/api/annotations_pb2.pyi",
        "google/api/auth_pb2.py",
        "google/api/auth_pb2.pyi",
        "google/api/backend_pb2.py",
        "google/api/backend_pb2.pyi",
        "google/api/billing_pb2.py",
        "google/api/billing_pb2.pyi",
        "google/api/client_pb2.py",
        "google/api/client_pb2.pyi",
        "google/api/config_change_pb2.py",
        "google/api/config_change_pb2.pyi",
        "google/api/consumer_pb2.py",
        "google/api/consumer_pb2.pyi",
        "google/api/context_pb2.py",
        "google/api/context_pb2.pyi",
        "google/api/control_pb2.py",
        "google/api/control_pb2.pyi",
        "google/api/distribution_pb2.py",
        "google/api/distribution_pb2.pyi",
        "google/api/documentation_pb2.py",
        "google/api/documentation_pb2.pyi",
        "google/api/endpoint_pb2.py",
        "google/api/endpoint_pb2.pyi",
        "google/api/error_reason_pb2.py",
        "google/api/error_reason_pb2.pyi",
        "google/api/field_behavior_pb2.py",
        "google/api/field_behavior_pb2.pyi",
        "google/api/field_info_pb2.py",
        "google/api/field_info_pb2.pyi",
        "google/api/http_pb2.py",
        "google/api/http_pb2.pyi",
        "google/api/httpbody_pb2.py",
        "google/api/httpbody_pb2.pyi",
        "google/api/label_pb2.py",
        "google/api/label_pb2.pyi",
        "google/api/launch_stage_pb2.py",
        "google/api/launch_stage_pb2.pyi",
        "google/api/log_pb2.py",
        "google/api/log_pb2.pyi",
        "google/api/logging_pb2.py",
        "google/api/logging_pb2.pyi",
        "google/api/metric_pb2.py",
        "google/api/metric_pb2.pyi",
        "google/api/monitored_resource_pb2.py",
        "google/api/monitored_resource_pb2.pyi",
        "google/api/monitoring_pb2.py",
        "google/api/monitoring_pb2.pyi",
        "google/api/policy_pb2.py",
        "google/api/policy_pb2.pyi",
        "google/api/quota_pb2.py",
        "google/api/quota_pb2.pyi",
        "google/api/resource_pb2.py",
        "google/api/resource_pb2.pyi",
        "google/api/routing_pb2.py",
        "google/api/routing_pb2.pyi",
        "google/api/service_pb2.py",
        "google/api/service_pb2.pyi",
        "google/api/source_info_pb2.py",
        "google/api/source_info_pb2.pyi",
        "google/api/system_parameter_pb2.py",
        "google/api/system_parameter_pb2.pyi",
        "google/api/usage_pb2.py",
        "google/api/usage_pb2.pyi",
        "google/api/visibility_pb2.py",
        "google/api/visibility_pb2.pyi",
        "google/cloud/common_resources_pb2.py",
        "google/cloud/common_resources_pb2.pyi",
        "google/cloud/extended_operations_pb2.py",
        "google/cloud/extended_operations_pb2.pyi",
        "google/cloud/location/locations_pb2.py",
        "google/cloud/location/locations_pb2.pyi",
        "google/gapic/metadata/gapic_metadata_pb2.py",
        "google/gapic/metadata/gapic_metadata_pb2.pyi",
        "google/logging/type/http_request_pb2.py",
        "google/logging/type/http_request_pb2.pyi",
        "google/logging/type/log_severity_pb2.py",
        "google/logging/type/log_severity_pb2.pyi",
        "google/longrunning/operations_grpc.py",
        "google/longrunning/operations_grpc_pb2.py",
        "google/longrunning/operations_pb2.py",
        "google/longrunning/operations_pb2_grpc.py",
        "google/longrunning/operations_proto.py",
        "google/longrunning/operations_proto_pb2.py",
        "google/longrunning/operations_proto_pb2.pyi",
        "google/rpc/code_pb2.py",
        "google/rpc/code_pb2.pyi",
        "google/rpc/context/attribute_context_pb2.py",
        "google/rpc/context/attribute_context_pb2.pyi",
        "google/rpc/context/audit_context_pb2.py",
        "google/rpc/context/audit_context_pb2.pyi",
        "google/rpc/error_details_pb2.py",
        "google/rpc/error_details_pb2.pyi",
        "google/rpc/http_pb2.py",
        "google/rpc/http_pb2.pyi",
        "google/rpc/status_pb2.py",
        "google/rpc/status_pb2.pyi",
        "google/type/calendar_period_pb2.py",
        "google/type/calendar_period_pb2.pyi",
        "google/type/color_pb2.py",
        "google/type/color_pb2.pyi",
        "google/type/date_pb2.py",
        "google/type/date_pb2.pyi",
        "google/type/datetime_pb2.py",
        "google/type/datetime_pb2.pyi",
        "google/type/dayofweek_pb2.py",
        "google/type/dayofweek_pb2.pyi",
        "google/type/decimal_pb2.py",
        "google/type/decimal_pb2.pyi",
        "google/type/expr_pb2.py",
        "google/type/expr_pb2.pyi",
        "google/type/fraction_pb2.py",
        "google/type/fraction_pb2.pyi",
        "google/type/interval_pb2.py",
        "google/type/interval_pb2.pyi",
        "google/type/latlng_pb2.py",
        "google/type/latlng_pb2.pyi",
        "google/type/localized_text_pb2.py",
        "google/type/localized_text_pb2.pyi",
        "google/type/money_pb2.py",
        "google/type/money_pb2.pyi",
        "google/type/month_pb2.py",
        "google/type/month_pb2.pyi",
        "google/type/phone_number_pb2.py",
        "google/type/phone_number_pb2.pyi",
        "google/type/postal_address_pb2.py",
        "google/type/postal_address_pb2.pyi",
        "google/type/quaternion_pb2.py",
        "google/type/quaternion_pb2.pyi",
        "google/type/timeofday_pb2.py",
        "google/type/timeofday_pb2.pyi",
    ],
    namespace_dirs = [
        "google/api",
        "google/cloud",
        "google/cloud/location",
        "google/gapic",
        "google/gapic/metadata",
        "google/logging",
        "google/logging/type",
        "google/longrunning",
        "google/rpc",
        "google/rpc/context",
        "google/type",
    ],
    visibility = ["//visibility:public"],
)

exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
