#!/bin/bash
# SCIE Launcher Template - Self-Contained Interpreted Executable
# Generated by py_scie_binary from rules_py
#
# This launcher handles:
# - Runfiles resolution (Bazel runfiles or standalone)
# - Interpreter resolution via runfiles (when include_interpreter=true)
# - Cross-platform execution

set -euo pipefail

# Runfiles initialization
{{BASH_RLOCATION_FN}}
if type runfiles_export_envvars &>/dev/null; then
    runfiles_export_envvars
fi

# Configuration from rule attributes
SCIE_NAME="{{SCIE_NAME}}"
INCLUDE_INTERPRETER={{INCLUDE_INTERPRETER}}
WORKSPACE_NAME="{{WORKSPACE_NAME}}"

# Find the script's directory
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR="$(pwd)"
fi

# Resolve the zipapp path
# Try multiple resolution strategies
resolve_zipapp() {
    local zipapp_rel="{{ZIPAPP_PATH}}"
    local candidates=()
    
    # Strategy 1: Relative to script directory
    candidates+=("$SCRIPT_DIR/$(basename "$zipapp_rel")")
    candidates+=("$SCRIPT_DIR/$zipapp_rel")
    
    # Strategy 2: Runfiles directory
    if [[ -n "${RUNFILES_DIR:-}" ]]; then
        candidates+=("$RUNFILES_DIR/$zipapp_rel")
        candidates+=("$RUNFILES_DIR/$WORKSPACE_NAME/$zipapp_rel")
    fi
    
    # Strategy 3: Use rlocation if available
    if type rlocation &>/dev/null; then
        local rloc
        rloc="$(rlocation "$zipapp_rel" 2>/dev/null || true)"
        [[ -n "$rloc" ]] && candidates+=("$rloc")
        
        # Try with workspace prefix
        rloc="$(rlocation "$WORKSPACE_NAME/$zipapp_rel" 2>/dev/null || true)"
        [[ -n "$rloc" ]] && candidates+=("$rloc")
    fi
    
    # Find first existing candidate
    for candidate in "${candidates[@]}"; do
        if [[ -f "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done
    
    return 1
}

ZIPAPP_PATH="$(resolve_zipapp)" || {
    echo "ERROR: Could not find zipapp for {{SCIE_NAME}}" >&2
    echo "Tried: {{ZIPAPP_PATH}}" >&2
    exit 1
}

# Function to resolve interpreter from runfiles
resolve_runfiles_interpreter() {
    local interpreter="{{INTERPRETER_PATH}}"
    local resolved=""
    
    # Try rlocation
    if type rlocation &>/dev/null; then
        resolved="$(rlocation "$interpreter" 2>/dev/null || true)"
        [[ -n "$resolved" && -x "$resolved" ]] && echo "$resolved" && return 0
    fi
    
    # Try runfiles directory
    if [[ -n "${RUNFILES_DIR:-}" ]]; then
        resolved="$RUNFILES_DIR/$interpreter"
        [[ -x "$resolved" ]] && echo "$resolved" && return 0
    fi
    
    return 1
}

# Main execution logic
determine_interpreter() {
    # Priority 1: Runfiles interpreter (includes interpreter files when include_interpreter=true)
    local runfiles_interp
    runfiles_interp="$(resolve_runfiles_interpreter 2>/dev/null)" && {
        echo "$runfiles_interp"
        return 0
    }
    
    # Priority 2: System Python
    # Try versioned first, then generic
    local system_candidates=(
        "python3"
        "python"
        "/usr/bin/python3"
        "/usr/bin/python"
        "/usr/local/bin/python3"
        "/usr/local/bin/python"
    )
    
    for python in "${system_candidates[@]}"; do
        if command -v "$python" &>/dev/null; then
            echo "$python"
            return 0
        fi
    done
    
    return 1
}

# Find the interpreter
PYTHON="$(determine_interpreter)" || {
    echo "ERROR: Could not find Python interpreter for {{SCIE_NAME}}" >&2
    echo "INCLUDE_INTERPRETER=$INCLUDE_INTERPRETER" >&2
    exit 1
}

# Verify the zipapp
if [[ ! -r "$ZIPAPP_PATH" ]]; then
    echo "ERROR: Cannot read zipapp at $ZIPAPP_PATH" >&2
    exit 1
fi

# Inject AspectPyInfo import paths into PYTHONPATH for robust module resolution.
# The zipapp __main__.py also injects these, but setting PYTHONPATH in the
# launcher ensures compatibility with direct zipapp execution scenarios.
_SCIE_IMPORTS="{{IMPORTS}}"
if [[ -n "${_SCIE_IMPORTS}" ]]; then
    _PYTHONPATH_EXTRA=""
    _IFS_OLD="$IFS"
    IFS=":"
    for _imp in ${_SCIE_IMPORTS}; do
        _path="${ZIPAPP_PATH}/${_imp}"
        if [[ -d "${_path}" && ":${_PYTHONPATH_EXTRA}:" != *":${_path}:"* ]]; then
            if [[ -z "${_PYTHONPATH_EXTRA}" ]]; then
                _PYTHONPATH_EXTRA="${_path}"
            else
                _PYTHONPATH_EXTRA="${_PYTHONPATH_EXTRA}:${_path}"
            fi
        fi
    done
    IFS="${_IFS_OLD}"
    if [[ -n "${_PYTHONPATH_EXTRA}" ]]; then
        export PYTHONPATH="${_PYTHONPATH_EXTRA}${PYTHONPATH:+:${PYTHONPATH}}"
    fi
fi

# Debug output (controlled by environment)
if [[ -n "${SCIE_DEBUG:-}" ]]; then
    echo "SCIE Debug: name=$SCIE_NAME" >&2
    echo "SCIE Debug: zipapp=$ZIPAPP_PATH" >&2
    echo "SCIE Debug: interpreter=$PYTHON" >&2
    echo "SCIE Debug: include_interpreter=$INCLUDE_INTERPRETER" >&2
    echo "SCIE Debug: pythonpath=$PYTHONPATH" >&2
fi

# Execute the zipapp
exec "$PYTHON" "$ZIPAPP_PATH" "$@"
