#!/bin/bash
# SCIE Launcher Template - Self-Contained Interpreted Executable
# Generated by py_scie_binary from rules_py
#
# This launcher handles:
# - Runfiles resolution (Bazel runfiles or standalone)
# - Interpreter caching (when include_interpreter=true)
# - Cross-platform execution

set -euo pipefail

# Runfiles initialization
{{BASH_RLOCATION_FN}}
if type runfiles_export_envvars &>/dev/null; then
    runfiles_export_envvars
fi

# Configuration from rule attributes
SCIE_NAME="{{SCIE_NAME}}"
INTERPRETER_HASH="{{INTERPRETER_HASH}}"
INCLUDE_INTERPRETER={{INCLUDE_INTERPRETER}}
WORKSPACE_NAME="{{WORKSPACE_NAME}}"

# Determine cache location for embedded interpreter
if [[ -n "${XDG_CACHE_HOME:-}" ]]; then
    CACHE_BASE="$XDG_CACHE_HOME"
elif [[ -n "${HOME:-}" ]]; then
    CACHE_BASE="$HOME/.cache"
else
    CACHE_BASE="/tmp"
fi
CACHE_DIR="$CACHE_BASE/rules_py_scie/$INTERPRETER_HASH"

# Find the script's directory
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR="$(pwd)"
fi

# Resolve the zipapp path
# Try multiple resolution strategies
resolve_zipapp() {
    local zipapp_rel="{{ZIPAPP_PATH}}"
    local candidates=()
    
    # Strategy 1: Relative to script directory
    candidates+=("$SCRIPT_DIR/$(basename "$zipapp_rel")")
    candidates+=("$SCRIPT_DIR/$zipapp_rel")
    
    # Strategy 2: Runfiles directory
    if [[ -n "${RUNFILES_DIR:-}" ]]; then
        candidates+=("$RUNFILES_DIR/$zipapp_rel")
        candidates+=("$RUNFILES_DIR/$WORKSPACE_NAME/$zipapp_rel")
    fi
    
    # Strategy 3: Use rlocation if available
    if type rlocation &>/dev/null; then
        local rloc
        rloc="$(rlocation "$zipapp_rel" 2>/dev/null || true)"
        [[ -n "$rloc" ]] && candidates+=("$rloc")
        
        # Try with workspace prefix
        rloc="$(rlocation "$WORKSPACE_NAME/$zipapp_rel" 2>/dev/null || true)"
        [[ -n "$rloc" ]] && candidates+=("$rloc")
    fi
    
    # Find first existing candidate
    for candidate in "${candidates[@]}"; do
        if [[ -f "$candidate" ]]; then
            echo "$candidate"
            return 0
        fi
    done
    
    return 1
}

ZIPAPP_PATH="$(resolve_zipapp)" || {
    echo "ERROR: Could not find zipapp for {{SCIE_NAME}}" >&2
    echo "Tried: {{ZIPAPP_PATH}}" >&2
    exit 1
}

# Function to extract and use embedded interpreter
use_embedded_interpreter() {
    local interpreter_tar=""
    local candidates=()
    
    # Find interpreter tarball
    candidates+=("$SCRIPT_DIR/interpreter.tar.gz")
    candidates+=("$SCRIPT_DIR/{{SCIE_NAME}}_interpreter.tar.gz")
    
    if [[ -n "${RUNFILES_DIR:-}" ]]; then
        candidates+=("$RUNFILES_DIR/interpreter.tar.gz")
        candidates+=("$RUNFILES_DIR/{{ZIPAPP_PATH}}.interpreter.tar.gz")
    fi
    
    for candidate in "${candidates[@]}"; do
        if [[ -f "$candidate" ]]; then
            interpreter_tar="$candidate"
            break
        fi
    done
    
    [[ -z "$interpreter_tar" ]] && return 1
    
    # Extract if not already cached
    if [[ ! -d "$CACHE_DIR/python/bin" ]]; then
        mkdir -p "$CACHE_DIR"
        
        # Extract with error handling
        if ! tar -xzf "$interpreter_tar" -C "$CACHE_DIR" 2>/dev/null; then
            rm -rf "$CACHE_DIR"
            return 1
        fi
        
        # Create marker file with extraction info
        date > "$CACHE_DIR/.extracted"
        echo "$INTERPRETER_HASH" > "$CACHE_DIR/.hash"
    fi
    
    # Find Python executable in extracted interpreter
    local python_candidates=(
        "$CACHE_DIR/python/bin/python3"
        "$CACHE_DIR/bin/python3"
        "$CACHE_DIR/python/bin/python"
        "$CACHE_DIR/bin/python"
    )
    
    for python in "${python_candidates[@]}"; do
        if [[ -x "$python" ]]; then
            echo "$python"
            return 0
        fi
    done
    
    return 1
}

# Function to resolve interpreter from runfiles
resolve_runfiles_interpreter() {
    local interpreter="{{INTERPRETER_PATH}}"
    local resolved=""
    
    # Try rlocation
    if type rlocation &>/dev/null; then
        resolved="$(rlocation "$interpreter" 2>/dev/null || true)"
        [[ -n "$resolved" && -x "$resolved" ]] && echo "$resolved" && return 0
    fi
    
    # Try runfiles directory
    if [[ -n "${RUNFILES_DIR:-}" ]]; then
        resolved="$RUNFILES_DIR/$interpreter"
        [[ -x "$resolved" ]] && echo "$resolved" && return 0
    fi
    
    return 1
}

# Main execution logic
determine_interpreter() {
    # Priority 1: Embedded interpreter (if enabled)
    if [[ "$INCLUDE_INTERPRETER" == "true" ]]; then
        local embedded
        embedded="$(use_embedded_interpreter 2>/dev/null)" && {
            echo "$embedded"
            return 0
        }
    fi
    
    # Priority 2: Runfiles interpreter
    local runfiles_interp
    runfiles_interp="$(resolve_runfiles_interpreter 2>/dev/null)" && {
        echo "$runfiles_interp"
        return 0
    }
    
    # Priority 3: System Python
    # Try versioned first, then generic
    local system_candidates=(
        "python3"
        "python"
        "/usr/bin/python3"
        "/usr/bin/python"
        "/usr/local/bin/python3"
        "/usr/local/bin/python"
    )
    
    for python in "${system_candidates[@]}"; do
        if command -v "$python" &>/dev/null; then
            echo "$python"
            return 0
        fi
    done
    
    return 1
}

# Find the interpreter
PYTHON="$(determine_interpreter)" || {
    echo "ERROR: Could not find Python interpreter for {{SCIE_NAME}}" >&2
    echo "INCLUDE_INTERPRETER=$INCLUDE_INTERPRETER" >&2
    exit 1
}

# Verify the zipapp
if [[ ! -r "$ZIPAPP_PATH" ]]; then
    echo "ERROR: Cannot read zipapp at $ZIPAPP_PATH" >&2
    exit 1
fi

# Debug output (controlled by environment)
if [[ -n "${SCIE_DEBUG:-}" ]]; then
    echo "SCIE Debug: name=$SCIE_NAME" >&2
    echo "SCIE Debug: zipapp=$ZIPAPP_PATH" >&2
    echo "SCIE Debug: interpreter=$PYTHON" >&2
    echo "SCIE Debug: include_interpreter=$INCLUDE_INTERPRETER" >&2
    echo "SCIE Debug: cache_dir=$CACHE_DIR" >&2
fi

# Execute the zipapp
exec "$PYTHON" "$ZIPAPP_PATH" "$@"
