load("@bazel_lib//:bzl_library.bzl", "bzl_library")
load("//py:defs.bzl", "py_library")

package(default_visibility = [
    "//uv/private:__subpackages__",
])

exports_files(
    ["build_helper.py"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "rule",
    srcs = ["rule.bzl"],
    deps = [
        "//py/private/toolchain:types",
        "//uv/private:source_built_wheel",
        "@bazel_lib//lib:resource_sets",
        "@rules_cc//cc:action_names_bzl",
        "@rules_cc//cc/common",
    ],
)

py_library(
    name = "memory_monitor",
    srcs = ["memory_monitor.py"],
    visibility = ["//visibility:public"],
)
