"""`bazel run`-able Cargo.lock generation for a Rust sdist.

sdist_build vendors the crates a Rust sdist's `Cargo.lock` pins so cargo
builds offline. An sdist that ships no lock (tiktoken) builds online with a
warning until the project supplies one through
`uv.override_package(cargo_lock = ...)`. This rule produces that file with
the toolchain the build itself uses: `bazel run` extracts the sdist, runs
`cargo generate-lockfile` on its manifest and copies the result into the
workspace. Every `sdist_build__*` repository generated for a Rust sdist
carries one as `:cargo_lock`.
"""

_SCRIPT = """#!/usr/bin/env bash
# Generated by aspect_rules_py: Cargo.lock for {sdist_name} with the project's Rust toolchain.
set -o errexit -o nounset -o pipefail

runfiles="${{RUNFILES_DIR:-$(cd .. && pwd)}}"
sdist="$runfiles/{sdist}"
cargo="$runfiles/{cargo}"
export RUSTC="$runfiles/{rustc}"

workspace="${{BUILD_WORKSPACE_DIRECTORY:-}}"
if [ -z "$workspace" ]; then
    echo "error: run this target with \\`bazel run\\`; it writes the lock into the workspace" >&2
    exit 1
fi
out="${{1:-{default_output}}}"
case "$out" in
    /*) ;;
    *) out="$workspace/$out" ;;
esac

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
case "$sdist" in
    *.zip) unzip -q "$sdist" -d "$work" ;;
    *) tar -xf "$sdist" -C "$work" ;;
esac
top="$(find "$work" -mindepth 1 -maxdepth 1 | LC_ALL=C sort | head -n 1)"

# The wheel build applies pre_build_patches before the backend reads the
# sources; the generated lock must describe the same patched graph, or an
# override that adds or upgrades a Cargo dependency would vendor crates the
# offline build cannot use.
{patch_cmds}

# The manifest the backend builds, resolved once by the configure tool
# (maturin's [tool.maturin] manifest-path, or the crate it names) instead of
# a shallowest-guess this script used to make independently.
manifest="$work/{manifest}"
if [ ! -f "$manifest" ]; then
    echo "error: {sdist_name}: resolved Cargo manifest '$manifest' is not in the sdist" >&2
    exit 1
fi

"$cargo" generate-lockfile --manifest-path "$manifest"
lock_dir="$(dirname "$("$cargo" locate-project --workspace --message-format plain --manifest-path "$manifest")")"
mkdir -p "$(dirname "$out")"
cp "$lock_dir/Cargo.lock" "$out"

echo "Wrote $out"
case "$out" in
    "$workspace"/*)
        rel="${{out#"$workspace"/}}"
        case "$rel" in
            */*) label="//${{rel%/*}}:${{rel##*/}}" ;;
            *) label="//:$rel" ;;
        esac
        echo "Declare it on the package so sdist_build vendors its crates and the build runs offline:"
        echo "  uv.override_package(name = \\"{package}\\", cargo_lock = \\"$label\\", lock = \\"<the project's uv.lock>\\")"
        ;;
    *)
        echo "Move it into the workspace and declare it with uv.override_package(name = \\"{package}\\", cargo_lock = \\"//...\\") so sdist_build vendors its crates."
        ;;
esac
"""

def _tool(toolchain, name):
    """A tool the toolchain exposes as a File, or via an executable target."""
    value = getattr(toolchain, name, None)
    if type(value) == "File":
        return value
    if value != None and DefaultInfo in value:
        return value[DefaultInfo].files_to_run.executable
    return None

def _runfiles_path(ctx, file):
    """`file` below the runfiles root, whichever repository it belongs to."""
    if file.short_path.startswith("../"):
        return file.short_path[len("../"):]
    return ctx.workspace_name + "/" + file.short_path

def _sdist_stem(basename):
    for suffix in (".tar.gz", ".tgz", ".tar.bz2", ".tar.xz", ".tar", ".zip"):
        if basename.endswith(suffix):
            return basename[:-len(suffix)]
    return basename

def _cargo_lock_generator_impl(ctx):
    toolchain = ctx.attr.rust_toolchain[platform_common.ToolchainInfo]
    cargo = _tool(toolchain, "cargo")
    rustc = _tool(toolchain, "rustc")
    if cargo == None or rustc == None:
        fail("{}: rust_toolchain {} exposes no cargo and rustc; it must be a rules_rust `rust_toolchain`, such as `current_rust_toolchain`.".format(ctx.label, ctx.attr.rust_toolchain.label))
    if not ctx.attr.manifest:
        fail("{}: the configure tool resolved no Cargo manifest for this sdist; it may not build Rust at all.".format(ctx.label))

    sdist_name = ctx.file.sdist.basename
    stem = _sdist_stem(sdist_name)
    package = stem.rsplit("-", 1)[0]
    patch_cmds = "".join([
        '(cd "$top" && patch --no-backup-if-mismatch -p{} -i "$runfiles/{}")\n'.format(ctx.attr.pre_build_patch_strip, _runfiles_path(ctx, patch))
        for patch in ctx.files.pre_build_patches
    ])
    script = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = script,
        content = _SCRIPT.format(
            sdist_name = sdist_name,
            sdist = _runfiles_path(ctx, ctx.file.sdist),
            cargo = _runfiles_path(ctx, cargo),
            rustc = _runfiles_path(ctx, rustc),
            manifest = ctx.attr.manifest,
            patch_cmds = patch_cmds,
            default_output = ctx.attr.output or stem + ".Cargo.lock",
            package = package,
        ),
        is_executable = True,
    )

    transitive = []
    all_files = getattr(toolchain, "all_files", None)
    if all_files:
        transitive.append(depset(all_files) if type(all_files) == "list" else all_files)
    runfiles = ctx.runfiles(
        files = [ctx.file.sdist, cargo, rustc] + list(ctx.files.pre_build_patches),
        transitive_files = depset(transitive = transitive),
    )
    default_runfiles = ctx.attr.rust_toolchain[DefaultInfo].default_runfiles
    if default_runfiles:
        runfiles = runfiles.merge(default_runfiles)
    return [DefaultInfo(executable = script, runfiles = runfiles)]

cargo_lock_generator = rule(
    implementation = _cargo_lock_generator_impl,
    doc = """`bazel run` this target to write the sdist's `Cargo.lock` into the workspace.

The lock is resolved with the project's own Rust toolchain (`cargo
generate-lockfile` on the manifest the configure tool resolved), over the
sdist with its `pre_build_patches` applied — the same patched sources the
wheel build sees. The first argument overrides the output path, relative to
the workspace root.""",
    executable = True,
    attrs = {
        "sdist": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The source distribution archive.",
        ),
        "rust_toolchain": attr.label(
            mandatory = True,
            providers = [platform_common.ToolchainInfo],
            doc = "A ruleset `rust_toolchain` exposing `cargo` and `rustc`; the project's `uv.rust_toolchain()`.",
        ),
        "manifest": attr.string(
            mandatory = True,
            doc = "The sdist member path of the Cargo.toml the backend builds, as resolved by the configure tool.",
        ),
        "pre_build_patches": attr.label_list(
            allow_files = True,
            doc = "Patches applied to the extracted sdist before the lock is resolved, the ones the wheel build applies.",
        ),
        "pre_build_patch_strip": attr.int(
            default = 1,
            doc = "The -p strip count for `pre_build_patches`.",
        ),
        "output": attr.string(
            default = "",
            doc = "Default workspace-relative output path. Empty: `<name>-<version>.Cargo.lock` at the workspace root.",
        ),
    },
)
