load("@bazel_lib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = [
        ":graph_utils",
        ":lockfile",
        ":projectfile",
        "//py/private/interpreter:resolve",
        "//uv/private:normalize_version",
        "//uv/private/constraints:repository",
        "//uv/private/git_archive:repository",
        "//uv/private/normalize:name",
        "//uv/private/sdist_build:attrs",
        "//uv/private/sdist_build:repository",
        "//uv/private/sdist_configure:defs",
        "//uv/private/tomltool:toml",
        "//uv/private/uv_hub:repository",
        "//uv/private/uv_project:repository",
        "//uv/private/whl_install:dist_repository",
        "//uv/private/whl_install:metadata",
        "//uv/private/whl_install:repository",
        "@bazel_lib//lib:resource_sets",
        "@bazel_skylib//lib:sets",
        "@bazel_tools//tools/build_defs/repo:http.bzl",
    ],
)

bzl_library(
    name = "graph_utils",
    srcs = ["graph_utils.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = [
        "//uv/private:normalize_version",
        "//uv/private/graph:sccs",
    ],
)

bzl_library(
    name = "lockfile",
    srcs = ["lockfile.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = [
        ":git_utils",
        ":marker_simplify",
        "//uv/private:normalize_version",
        "//uv/private:parse_whl_name",
        "//uv/private:sha1",
        "//uv/private/constraints/platform:defs",
        "//uv/private/constraints/python:defs",
        "//uv/private/normalize:name",
        "//uv/private/whl_install:repository",
    ],
)

bzl_library(
    name = "marker_simplify",
    srcs = ["marker_simplify.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = ["//uv/private/markers:pep508_evaluate"],
)

bzl_library(
    name = "projectfile",
    srcs = ["projectfile.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = [
        ":dep_groups",
        "//uv/private/normalize:name",
        "//uv/private/versions",
    ],
)

bzl_library(
    name = "uv_bin",
    srcs = ["uv_bin.bzl"],
    visibility = ["//uv:__subpackages__"],
    deps = [
        "//uv/private/toolchain:repositories",
        "//uv/private/toolchain:versions",
    ],
)

bzl_library(
    name = "dep_groups",
    srcs = ["dep_groups.bzl"],
    visibility = ["//uv:__subpackages__"],
)

bzl_library(
    name = "git_utils",
    srcs = ["git_utils.bzl"],
    visibility = ["//uv:__subpackages__"],
)
