#!/usr/bin/env python3
"""Import every top-500 distribution to add Python-side import cost on
top of the venv-build measurement. Distribution -> importable module
mapping is resolved at runtime via importlib.metadata so name munging
(`python-dateutil` -> `dateutil`, etc.) is automatic.

Individual import failures are tolerated and reported at the end so the
test still produces a stable signal even when one package can't load on
the current platform.

Also reports wall time from the test-process spawn to the start of this
body — captures launcher overhead (especially v1.11.5 py_test's runtime
venv assembly), Python interpreter init, site.py / .pth walk.
"""

import time

_T_PERF_AT_BODY = time.perf_counter()
_T_WALL_AT_BODY = time.time()

import importlib
import importlib.metadata
import sys

import psutil

_proc = psutil.Process()
_spawn_to_body = _T_WALL_AT_BODY - _proc.create_time()

DISTRIBUTIONS = [
    'boto3',
    'packaging',
    'urllib3',
    'certifi',
    'requests',
    'typing-extensions',
    'idna',
    'charset-normalizer',
    'setuptools',
    'botocore',
    'cryptography',
    'aiobotocore',
    'python-dateutil',
    'six',
    'pyyaml',
    'cffi',
    'pydantic',
    'pygments',
    'click',
    'numpy',
    'grpcio-status',
    'pycparser',
    'pydantic-core',
    'pluggy',
    's3transfer',
    'protobuf',
    'anyio',
    'attrs',
    'h11',
    'fsspec',
    'annotated-types',
    'pytest',
    'pandas',
    'httpx',
    'iniconfig',
    'httpcore',
    's3fs',
    'typing-inspection',
    'markupsafe',
    'platformdirs',
    'python-dotenv',
    'pip',
    'jinja2',
    'pyjwt',
    'jmespath',
    'importlib-metadata',
    'rich',
    'filelock',
    'aiohttp',
    'zipp',
    'pathspec',
    'wheel',
    'jsonschema',
    'markdown-it-py',
    'pytz',
    'pyasn1',
    'multidict',
    'yarl',
    'mdurl',
    'googleapis-common-protos',
    'starlette',
    'uvicorn',
    'google-auth',
    'rpds-py',
    'tzdata',
    'propcache',
    'frozenlist',
    'referencing',
    'pillow',
    'tqdm',
    'google-api-core',
    'jsonschema-specifications',
    'virtualenv',
    'aiosignal',
    'grpcio',
    'fastapi',
    'annotated-doc',
    'colorama',
    'aiohappyeyeballs',
    'awscli',
    'greenlet',
    'pyasn1-modules',
    'pyarrow',
    'requests-oauthlib',
    'wrapt',
    'opentelemetry-api',
    'scipy',
    'tomli',
    'tenacity',
    'pyparsing',
    'trove-classifiers',
    'sqlalchemy',
    'opentelemetry-semantic-conventions',
    'opentelemetry-sdk',
    'typer',
    'beautifulsoup4',
    'shellingham',
    'websockets',
    'oauthlib',
    'soupsieve',
    'psutil',
    'python-multipart',
    'lxml',
    'sniffio',
    'regex',
    'pydantic-settings',
    'rsa',
    'cachetools',
    'exceptiongroup',
    'more-itertools',
    'litellm',
    'requests-toolbelt',
    'distlib',
    'proto-plus',
    'tomlkit',
    'hatchling',
    'grpcio-tools',
    'docutils',
    'websocket-client',
    'openai',
    'openpyxl',
    'mypy-extensions',
    'et-xmlfile',
    'watchfiles',
    'opentelemetry-proto',
    'werkzeug',
    'distro',
    'jiter',
    'coverage',
    'google-cloud-storage',
    'mcp',
    'networkx',
    'wcwidth',
    'msgpack',
    'dnspython',
    'langchain',
    'huggingface-hub',
    'opentelemetry-exporter-otlp-proto-http',
    'decorator',
    'pyopenssl',
    'ptyprocess',
    'sglang',
    'smmap',
    'pexpect',
    'redis',
    'psycopg2-binary',
    'gitpython',
    'sse-starlette',
    'textual',
    'fonttools',
    'editables',
    'pynacl',
    'google-genai',
    'sortedcontainers',
    'matplotlib',
    'docker',
    'python-discovery',
    'tabulate',
    'flask',
    'kiwisolver',
    'async-timeout',
    'scikit-learn',
    'ruff',
    'opentelemetry-exporter-otlp-proto-common',
    'keyring',
    'isodate',
    'gitdb',
    'google-cloud-core',
    'opentelemetry-exporter-otlp-proto-grpc',
    'prompt-toolkit',
    'joblib',
    'contourpy',
    'docstring-parser',
    'itsdangerous',
    'jaraco-classes',
    'opentelemetry-instrumentation',
    'multiprocess',
    'secretstorage',
    'jeepney',
    'bcrypt',
    'azure-identity',
    'pytest-cov',
    'threadpoolctl',
    'uvloop',
    'azure-core',
    'google-resumable-media',
    'google-crc32c',
    'chardet',
    'httpx-sse',
    'orjson',
    'jaraco-context',
    'alembic',
    'dill',
    'blinker',
    'jaraco-functools',
    'msal',
    'defusedxml',
    'cycler',
    'deprecated',
    'zstandard',
    'hf-xet',
    'poetry-core',
    'ruamel-yaml',
    'kubernetes',
    'snowflake-connector-python',
    'pytest-asyncio',
    'email-validator',
    'httptools',
    'tzlocal',
    'types-requests',
    'toml',
    'nodeenv',
    'ipython',
    'rapidfuzz',
    'sympy',
    'mako',
    'jsonpointer',
    'pyproject-hooks',
    'prometheus-client',
    'google-api-python-client',
    'tokenizers',
    'uv',
    'asn1crypto',
    'mypy',
    'build',
    'setuptools-scm',
    'tiktoken',
    'google-cloud-aiplatform',
    'backoff',
    'pydantic-ai-slim',
    'google-auth-oauthlib',
    'uritemplate',
    'mpmath',
    'google-cloud-bigquery',
    'google-auth-httplib2',
    'paramiko',
    'identify',
    'cfgv',
    'traitlets',
    'pre-commit',
    'parso',
    'fastjsonschema',
    'httplib2',
    'transformers',
    'opentelemetry-exporter-otlp',
    'jedi',
    'executing',
    'marshmallow',
    'xxhash',
    'tree-sitter',
    'sqlparse',
    'cloudpickle',
    'asttokens',
    'matplotlib-inline',
    'opentelemetry-util-http',
    'opentelemetry-instrumentation-requests',
    'tornado',
    'grpc-google-iam-v1',
    'babel',
    'durationpy',
    'pytest-xdist',
    'aiofiles',
    'msal-extensions',
    'h2',
    'gunicorn',
    'pure-eval',
    'hyperframe',
    'stack-data',
    'hpack',
    'cython',
    'execnet',
    'jsonpatch',
    'black',
    'google-cloud-secret-manager',
    'asgiref',
    'azure-storage-blob',
    'authlib',
    'xmltodict',
    'markdown',
    'vcs-versioning',
    'sentry-sdk',
    'termcolor',
    'databricks-sdk',
    'webencodings',
    'nest-asyncio',
    'py4j',
    'google-cloud-batch',
    'importlib-resources',
    'anthropic',
    'datasets',
    'python-json-logger',
    'langchain-core',
    'weaviate-client',
    'pytest-json-ctrf',
    'tree-sitter-languages',
    'cachecontrol',
    'google-analytics-admin',
    'debugpy',
    'typing-inspect',
    'dbt-core',
    'pyzmq',
    'watchdog',
    'pymongo',
    'databricks-sql-connector',
    'librt',
    'pyee',
    'pytest-mock',
    'gcsfs',
    'isort',
    'jsonschema-path',
    'aioitertools',
    'dbt-adapters',
    'google-cloud-compute',
    'dulwich',
    'mccabe',
    'awswrangler',
    'google-cloud-kms',
    'pycryptodome',
    'pandas-stubs',
    'lz4',
    'playwright',
    'slack-sdk',
    'pymysql',
    'tinycss2',
    'installer',
    'pkginfo',
    'torch',
    'flatbuffers',
    'grpcio-health-checking',
    'pathable',
    'dataclasses-json',
    'narwhals',
    'deepdiff',
    'jupyter-core',
    'pyperclip',
    'ydb',
    'langsmith',
    'msrest',
    'typedload',
    'pymupdf',
    'rfc3339-validator',
    'jsonpath-ng',
    'google-cloud-dlp',
    'pygithub',
    'google-cloud-speech',
    'pycodestyle',
    'poetry',
    'dbt-common',
    'ruamel-yaml-clib',
    'ipykernel',
    'structlog',
    'types-pyyaml',
    'xlsxwriter',
    'invoke',
    'jupyter-client',
    'safetensors',
    'loguru',
    'semver',
    'pydantic-graph',
    'jsonref',
    'cyclopts',
    'arrow',
    'crashtest',
    'google-cloud-pubsub',
    'rich-toolkit',
    'google-cloud-monitoring',
    'argcomplete',
    'comm',
    'sphinx',
    'beartype',
    'asyncpg',
    'text-unidecode',
    'shapely',
    'python-slugify',
    'cleo',
    'smart-open',
    'brotli',
    'pytokens',
    'rich-rst',
    'pendulum',
    'notebook',
    'types-protobuf',
    'backports-tarfile',
    'wsproto',
    'graphql-core',
    'future',
    'fastmcp',
    'cattrs',
    'datadog',
    'mistune',
    'lark',
    'ujson',
    'google-cloud-tasks',
    'google-cloud-logging',
    'simplejson',
    'requests-file',
    'croniter',
    'ipython-pygments-lexers',
    'poetry-plugin-export',
    'google-cloud-resource-manager',
    'faker',
    'google-cloud-bigtable',
    'google-cloud-vision',
    'opensearch-py',
    'onnxruntime',
    'bleach',
    'nbformat',
    'xlrd',
    'deprecation',
    'py',
    'argon2-cffi-bindings',
    'argon2-cffi',
    'azure-common',
    'snowflake-sqlalchemy',
    'pyflakes',
    'typeguard',
    'psycopg',
    'langchain-openai',
    'cbor2',
    'google-cloud-texttospeech',
    'mdit-py-plugins',
    'pysocks',
    'google-cloud-workflows',
    'sqlalchemy-bigquery',
    'google-cloud-language',
    'google-cloud-videointelligence',
    'responses',
    'plotly',
    'scramp',
    'nbconvert',
    'google-cloud-redis',
    'google-cloud-dataform',
    'numba',
    'google-cloud-os-login',
    'py-key-value-aio',
    'sqlglot',
    'llvmlite',
    'opentelemetry-instrumentation-fastapi',
    'zope-interface',
    'pycryptodomex',
    'linkify-it-py',
    'pbs-installer',
    'types-toml',
    'colorlog',
    'json5',
    'nltk',
    'requests-aws4auth',
    'absl-py',
    'google-cloud-memcache',
    'triton',
    'pytest-timeout',
    'toolz',
    'selenium',
    'opentelemetry-instrumentation-asgi',
    'dacite',
    'opentelemetry-exporter-prometheus',
    'uc-micro-py',
    'fastuuid',
    'uuid-utils',
    'flake8',
    'nbclient',
    'google-ads',
    'psycopg-binary',
    'confluent-kafka',
    'setproctitle',
    'pypdf',
    'joserfc',
    'tomli-w',
    'seaborn',
    'uncalled-for',
    'mmh3',
    'types-python-dateutil',
    'jupyterlab',
    'orderly-set',
    'async-lru',
    'openapi-pydantic',
    'jupyter-server',
    'humanize',
    'types-certifi',
    'flask-cors',
    'findpython',
    'pywin32',
    'pandocfilters',
    'elasticsearch',
    'jupyterlab-pygments',
    'ecdsa',
    'polars',
    'google-cloud-run',
    'pyspark',
    'inflection',
    'python-docx',
    'ray',
    'grpclib',
    'aws-sam-translator',
    'kombu',
    'altair',
    'click-plugins',
    'cfn-lint',
    'types-awscrt',
    'celery',
]


def top_level_modules(dist_name: str) -> list[str]:
    try:
        dist = importlib.metadata.distribution(dist_name)
    except Exception:  # noqa: BLE001
        return []
    try:
        top = dist.read_text("top_level.txt")
    except Exception:  # noqa: BLE001
        top = None
    if top:
        return [m for m in top.splitlines() if m and not m.startswith("_")]
    name = (dist.metadata or {}).get("Name") if dist.metadata else None
    if not name:
        name = dist_name
    return [name.replace("-", "_").replace(".", "_")]


def main() -> int:
    ok, missing, failed = 0, [], []
    start = time.perf_counter()
    for dist in DISTRIBUTIONS:
        mods = top_level_modules(dist)
        if not mods:
            missing.append(dist)
            continue
        for mod in mods:
            try:
                importlib.import_module(mod)
                ok += 1
                break
            except Exception as e:  # noqa: BLE001
                failed.append((dist, mod, type(e).__name__))
    elapsed = time.perf_counter() - start
    print(f"spawn_to_body_wall    {_spawn_to_body * 1000:.1f} ms")
    print(f"imported {ok}/{len(DISTRIBUTIONS)} in {elapsed:.2f}s")
    if missing:
        print(f"missing dist metadata: {len(missing)}")
    if failed:
        print(f"import errors: {len(failed)}")
        for dist, mod, err in failed[:20]:
            print(f"  {dist} ({mod}): {err}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

print("1")
print("1")
print("1")
