load("@aspect_rules_py//py:defs.bzl", "py_test")
load("@bazel_skylib//rules:build_test.bzl", "build_test")

py_test(
    name = "test_a",
    srcs = ["test_a.py"],
    dep_group = "ambig-a",
    main = "test_a.py",
    deps = [
        "@pypi_uv_conflict_817//packaging",
    ],
)

py_test(
    name = "test_a_venv_test",
    srcs = ["test_a.py"],
    dep_group = "ambig-a",
    expose_venv = True,
    isolated = False,
    main = "test_a.py",
    deps = [
        "@pypi_uv_conflict_817//packaging",
    ],
)

py_test(
    name = "test_b",
    srcs = ["test_b.py"],
    dep_group = "ambig-b",
    main = "test_b.py",
    deps = [
        "@pypi_uv_conflict_817//packaging",
    ],
)

py_test(
    name = "test_b_venv_test",
    srcs = ["test_b.py"],
    dep_group = "ambig-b",
    expose_venv = True,
    isolated = False,
    main = "test_b.py",
    deps = [
        "@pypi_uv_conflict_817//packaging",
    ],
)

build_test(
    name = "source_build_21_3_test",
    targets = ["@sdist_build__ambig__packaging__21_3//:whl"],
)

build_test(
    name = "source_build_24_0_test",
    targets = ["@sdist_build__ambig__packaging__24_0//:whl"],
)

build_test(
    name = "version_constrained_source_build_test",
    targets = ["@sdist_build__ambig__cowsay__6_0//:whl"],
)
