load("@bazel_lib//:bzl_library.bzl", "bzl_library")

package(default_visibility = [
    "//docs:__pkg__",
    "//uv/private:__subpackages__",
])

bzl_library(
    name = "build_deps",
    srcs = ["build_deps.bzl"],
    deps = ["//uv/private/pprint:defs"],
)

bzl_library(
    name = "repository",
    srcs = ["repository.bzl"],
    deps = [
        ":build_deps",
        ":select_gen",
        "//uv/private/pprint:defs",
    ],
)

bzl_library(
    name = "select_gen",
    srcs = ["select_gen.bzl"],
)
