load("@aspect_rules_py//py:defs.bzl", "py_test")

py_test(
    name = "test",
    srcs = ["__test__.py"],
    dep_group = "venv-bin-scripts-423",
    include_console_scripts = True,
    main = "__test__.py",
    python_version = "3.11",
    deps = [
        "@pypi_venv_bin_scripts_423//dice",
        "@pypi_venv_bin_scripts_423//invoke",
    ],
)

py_test(
    name = "venv_test",
    srcs = ["__test__.py"],
    dep_group = "venv-bin-scripts-423",
    expose_venv = True,
    include_console_scripts = True,
    isolated = False,
    main = "__test__.py",
    python_version = "3.11",
    deps = [
        "@pypi_venv_bin_scripts_423//dice",
        "@pypi_venv_bin_scripts_423//invoke",
    ],
)
