use std::{fs::File, io::Read, path::Path};

use miette::{Context, IntoDiagnostic, Result};

/// Normalized forms of common PEP-420 namespace package `__init__.py` stubs.
///
/// These patterns ignore comments, whitespace, statement separators, and single
/// vs double quotes. Wheels sometimes differ only in those superficial ways,
/// which should not be treated as a real conflict.
///
/// The most common form is generated by setuptools:
///
/// ```text
/// __path__ = __import__('pkgutil').extend_path(__path__, __name__)
/// ```
const NAMESPACE_INIT_PATTERNS: &[&str] = &[
    "__path__=__import__(\"pkgutil\").extend_path(__path__,__name__)",
    "importpkgutil__path__=pkgutil.extend_path(__path__,__name__)",
    "__import__(\"pkg_resources\").declare_namespace(__name__)",
    "importpkg_resourcespkg_resources.declare_namespace(__name__)",
    "try:__import__(\"pkg_resources\").declare_namespace(__name__)exceptImportError:__import__(\"pkgutil\").extend_path(__path__,__name__)",
    "frompkgutilimportextend_path__path__=extend_path(__path__,__name__)",
];

/// Normalize the contents of a candidate namespace package `__init__.py`.
///
/// This is intentionally conservative: it only strips the superficial
/// differences that are known to vary between wheels (comments, whitespace,
/// quote style). It does *not* parse Python, so any stub with additional
/// executable code will fail to match the known patterns and will be treated
/// as a regular file.
fn normalize_init_content(content: &str) -> String {
    content
        .lines()
        .map(|line| line.split('#').next().unwrap_or(""))
        .flat_map(|line| line.chars())
        .filter(|c| !c.is_whitespace() && *c != ';')
        .map(|c| if c == '\'' { '"' } else { c })
        .collect()
}

/// Return `true` if `path` is a `__init__.py` that contains only a known
/// namespace package stub.
pub fn is_namespace_init(path: &Path) -> Result<bool> {
    if path.file_name() != Some(std::ffi::OsStr::new("__init__.py")) {
        return Ok(false);
    }
    let content = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return Ok(false),
    };
    let normalized = normalize_init_content(&content);
    Ok(NAMESPACE_INIT_PATTERNS
        .iter()
        .any(|pattern| normalized == *pattern))
}

/// Compare two files byte-for-byte.
fn files_are_byte_equal(p1: &Path, p2: &Path) -> Result<bool> {
    let mut f1 = File::open(p1)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p1.display()))?;
    let mut f2 = File::open(p2)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p2.display()))?;

    let len1 = f1.metadata().into_diagnostic()?.len();
    let len2 = f2.metadata().into_diagnostic()?.len();
    if len1 != len2 {
        return Ok(false);
    }

    let mut buf1 = [0u8; 8192];
    let mut buf2 = [0u8; 8192];

    loop {
        let n1 = f1.read(&mut buf1).into_diagnostic()?;
        let n2 = f2.read(&mut buf2).into_diagnostic()?;
        if n1 != n2 {
            return Ok(false);
        }
        if n1 == 0 {
            return Ok(true);
        }
        if buf1[..n1] != buf2[..n2] {
            return Ok(false);
        }
    }
}

/// Return `true` if two files should be considered the same for collision
/// detection purposes.
///
/// Files at the same path are trivially equivalent. If both files are
/// `__init__.py` namespace package stubs, they are treated as equivalent even
/// when their bytes differ only in comments, whitespace, or quote style.
/// Otherwise the files are compared byte-for-byte.
pub fn are_files_equivalent(p1: &Path, p2: &Path) -> Result<bool> {
    if p1 == p2 {
        return Ok(true);
    }

    if is_namespace_init(p1)? && is_namespace_init(p2)? {
        return Ok(true);
    }

    files_are_byte_equal(p1, p2)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn write_init(dir: &Path, content: &str) -> PathBuf {
        fs::create_dir_all(dir).unwrap();
        let path = dir.join("__init__.py");
        fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn recognizes_pkgutil_stub() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("jaraco"),
            "__path__ = __import__('pkgutil').extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn recognizes_pkgutil_stub_with_comments_and_whitespace() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("jaraco"),
            "# namespace package\n\n__path__ = __import__('pkgutil').extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn recognizes_pkgutil_stub_with_double_quotes() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("jaraco"),
            "__path__ = __import__(\"pkgutil\").extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn recognizes_import_pkgutil_form() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("jaraco"),
            "import pkgutil; __path__ = pkgutil.extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn recognizes_pkg_resources_fallback_stub() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("jaraco"),
            "try:\n    __import__('pkg_resources').declare_namespace(__name__)\nexcept ImportError:\n    __import__('pkgutil').extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn recognizes_from_pkgutil_extend_path_stub() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("backports"),
            "# See https://pypi.python.org/pypi/backports\n\nfrom pkgutil import extend_path\n__path__ = extend_path(__path__, __name__)\n",
        );
        assert!(is_namespace_init(&init).unwrap());
    }

    #[test]
    fn rejects_non_stub_init() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(&tmp.path().join("pkg"), "__version__ = '1.0.0'\n");
        assert!(!is_namespace_init(&init).unwrap());
    }

    #[test]
    fn rejects_init_with_extra_code() {
        let tmp = TempDir::new().unwrap();
        let init = write_init(
            &tmp.path().join("pkg"),
            "__path__ = __import__('pkgutil').extend_path(__path__, __name__)\nprint('hello')\n",
        );
        assert!(!is_namespace_init(&init).unwrap());
    }

    #[test]
    fn equivalent_stubs_differ_only_by_comments_and_quotes() {
        let tmp = TempDir::new().unwrap();
        let a = write_init(
            &tmp.path().join("a"),
            "# generated\n__path__ = __import__('pkgutil').extend_path(__path__, __name__)\n",
        );
        let b = write_init(
            &tmp.path().join("b"),
            "__path__ = __import__(\"pkgutil\").extend_path(__path__, __name__)\n",
        );
        assert!(are_files_equivalent(&a, &b).unwrap());
    }

    #[test]
    fn non_stubs_compared_byte_for_byte() {
        let tmp = TempDir::new().unwrap();
        let a = write_init(&tmp.path().join("a"), "x = 1\n");
        let b = write_init(&tmp.path().join("b"), "x = 2\n");
        assert!(!are_files_equivalent(&a, &b).unwrap());

        let c = write_init(&tmp.path().join("c"), "x = 1\n");
        assert!(are_files_equivalent(&a, &c).unwrap());
    }

    #[test]
    fn non_init_files_compared_byte_for_byte() {
        let tmp = TempDir::new().unwrap();
        let a = tmp.path().join("a.py");
        let b = tmp.path().join("b.py");
        fs::write(&a, "# comment\n").unwrap();
        fs::write(&b, "# comment\n").unwrap();
        assert!(are_files_equivalent(&a, &b).unwrap());

        fs::write(&b, "# different\n").unwrap();
        assert!(!are_files_equivalent(&a, &b).unwrap());
    }
}
