"""

Wheel installation repos are actually a bit tricky because this is where we go
from wheel files to a filegroup/py_library. That means we have to perform
platform wheel selection here as well as invoking the installation action to
produce a filegroup/TreeArtifact.

Metadata extraction (top-level names, console scripts, native layout) is NOT
done here: it lives in the per-wheel `whl_dist` repo so only the wheel a
configuration actually selects is fetched and inspected. This repo just picks
the right wheel and wires it into the `whl_install` build rule, which reads the
selected wheel's `PyWheelMetadataInfo`.

"""

load("//uv/private:parse_whl_name.bzl", "parse_whl_name")
load("//uv/private/constraints:defs.bzl", "MAJORS", "MINORS")
load("//uv/private/constraints/platform:defs.bzl", "supported_platform")
load("//uv/private/constraints/python:defs.bzl", "supported_python")
load("//uv/private/pprint:defs.bzl", "indent", "pprint")

def select_key(triple):
    """Force (triple, target) pairs into a orderable form.

    In order to impose _sequential_ selection on whl arms, we need to impose an
    ordering on platform triples. The way we do this is by coercing "platform
    triples" into:

    - The interpreter (major, minor) pair which  is orderable
    - _assuming_ that platform versions are lexically orderable
    - _assuming_ that ABI is effectively irrelevant to ordering

    This allows us to produce a tuple which will sort roughly according to the
    desired preference order among wheels which COULD be compatible with the
    same platform.

    """

    python, platform, abi = triple

    # Build a key for the interpreter
    py_major = int(python[2])
    py_minor = int(python[3:]) if python[3:] else 0
    py = (py_major, py_minor)

    # FIXME: It'd be WAY better if we could enforce a stronger order here
    platform = platform.split("_")
    if platform[0] in ["manylinux", "musllinux", "macosx"]:
        platform = (int(platform[1]), int(platform[2]))
    else:
        # Really case of windows; potential BSD issues?
        platform = (0, 0)

    # Build a key for the ABI.
    #
    # We want to prefer the most specific (eg. cp312t) build over a more generic
    # build (cp312). In order to achieve this, we check the ABI string for
    # specific feature flags and we set those flags to 1 rather than 0 before
    # including them in the sorting key.
    d = 1 if "d" in abi else 0
    m = 1 if "m" in abi else 0
    t = 1 if "t" in abi else 0
    u = 1 if "u" in abi else 0

    # In order to get the most specific match first, we score the abi by the
    # number of flags set and we sort wheels with highly specific ABIs first.
    flags = (d + m + t + u)
    abi = (flags, d, m, t, u, abi)

    return (py, platform, abi)

def sort_select_arms(arms):
    # {(python, platform, abi): target}
    pairs = sorted(arms.items(), key = lambda kv: select_key(kv[0]), reverse = True)
    return {a: b for a, b in pairs}

def compatible_python_tags(python_tag, abi_tag):
    if abi_tag != "abi3" or not python_tag.startswith("cp"):
        return [python_tag]

    major = int(python_tag[2])
    minor = int(python_tag[3:]) if python_tag[3:] else 0
    if major not in MAJORS:
        return [python_tag]
    return ["cp{}{}".format(major, m) for m in MINORS if m >= minor] or [python_tag]

def source_specificity(python_tag):
    """Score how specific a wheel's source python_tag is.

    Two abi3 wheels can expand into the same (compatible_python, platform,
    abi) key — e.g. both a cp38-abi3 and a cp311-abi3 wheel cover cp312+.
    Among those, the wheel with the higher minimum-CPython requirement is
    the most specific match and should win. Returned as an orderable tuple.
    """
    if not python_tag.startswith("cp"):
        return (0, 0)
    major = int(python_tag[2])
    minor = int(python_tag[3:]) if python_tag[3:] else 0
    return (major, minor)

def _whl_install_impl(repository_ctx):
    """Selects a compatible wheel for the host platform and defines its installation.

    This rule takes a dictionary of available pre-built wheels and an optional
    wheel built from source (`sbuild`). It is responsible for generating the
    logic to select the single, most appropriate wheel for the current target
    platform.

    It generates a `BUILD.bazel` file that:
    1.  Uses a custom `select_chain` rule to create a sequence of `select`
        statements. This chain checks the current platform against the
        compatibility triples of the available wheels (using the `config_setting`s
        generated by `configurations_hub`) and picks the first, most specific match.
    2.  If an `sbuild` target is provided, it is used as the default fallback in
        the selection chain, for when no pre-built wheel is compatible.
    3.  Feeds the selected wheel file into a `whl_install` build rule, which is
        responsible for unpacking the wheel into a directory. Each wheel is a
        `whl_dist` target carrying its own `PyWheelMetadataInfo`; the build rule
        reads the layout of whichever wheel this select resolved to.
    4.  Provides a final `install` alias that represents the installed content of
        the chosen wheel.

    Args:
        repository_ctx: The repository context.
    """
    prebuilds = json.decode(repository_ctx.attr.whls)
    # Prebuilds is a mapping from whl file name to repo labels which contain
    # that file. We need to take these wheel files and parse out compatibility.
    #
    # This is complicated by Starlark as with Python not treating lists as
    # values, so we have to go to strings of JSON in order to get value
    # semantics which is frustrating.

    # The strategy here is to roll through the wheels,
    select_arms = {}
    content = [
        "load(\"@aspect_rules_py//py:defs.bzl\", \"py_library\")",
        "load(\"@aspect_rules_py//uv/private/whl_install:defs.bzl\", \"select_chain\")",
        "load(\"@aspect_rules_py//uv/private/whl_install:rule.bzl\", \"source_built_wheel\", \"whl_install\")",
    ]

    # During expansion the value is (source_specificity, target). When two
    # abi3 wheels claim the same (compatible_python, platform, abi) key —
    # e.g. cp38-abi3 and cp311-abi3 both expand into cp312+ — the wheel
    # with the higher source minor must win, regardless of iteration order.
    for whl, target in prebuilds.items():
        parsed = parse_whl_name(whl)

        # FIXME: Make it impossible to generate absurd combinations such as
        # cp212-none-cp312 with unsatisfiable version specs.
        for platform_tag in parsed.platform_tags:
            # Escape hatch for ignoring weird unsupported platforms
            if not supported_platform(platform_tag):
                continue

            for abi_tag in parsed.abi_tags:
                for python_tag in parsed.python_tags:
                    specificity = source_specificity(python_tag)
                    for compatible_python_tag in compatible_python_tags(python_tag, abi_tag):
                        # Escape hatch for ignoring unsupported interpreters
                        if not supported_python(compatible_python_tag):
                            continue

                        key = (compatible_python_tag, platform_tag, abi_tag)
                        existing = select_arms.get(key)
                        if existing == None or specificity > existing[0]:
                            select_arms[key] = (specificity, target)

    # Strip the bookkeeping specificity score; downstream only needs the target.
    select_arms = {k: v[1] for k, v in select_arms.items()}

    # Unfortunately the way that Bazel decides ambiguous selects is explicitly
    # NOT designed to allow for the implementation of ranges. Because that would
    # be too easy. The disambiguation criteria is based on the number of
    # ultimately matching ground conditions, with the most matching winning. No
    # attention is paid to "how far away" those conditions may be down a select
    # chain, for instance down a range ladder.
    #
    # So we have to implement a select with ordering ourselves by testing one
    # condition at a time and taking the first mapped target for the first
    # matching condition.
    #
    # But how do we put all the potential options in an order such that the
    # first match is also the most relevant or newest match? We don't want to
    # take a build which targets glibc 2.0 forever for instance.
    #
    # The answer is that we have to apply a sorting logic. Specifically we need
    # to sort the platform.
    #
    # The wheel files -> targets pairs come in sorted descending order here, and
    # the wheel name parser reports the annotations also in sorted descending
    # order. So it happens that we SHOULD have the correct behavior here because
    # our insertion order into the select arms dict follows the required
    # newest-match order, but more assurance would be an improvement.
    #
    # Sort triples
    select_arms = sort_select_arms(select_arms)

    # FIXME: Insert the sbuild if it exists with an sbuild config flag as the
    # first condition so that the user can force the build to use _only_ sbuilds
    # if available (or transition a target to mandate sbuild).

    # Convert triples to conditions
    select_arms = {
        "@aspect_rules_py_pip_configurations//:{}-{}-{}".format(*k): v
        for k, v in select_arms.items()
    }

    sbuild_target = str(repository_ctx.attr.sbuild) if repository_ctx.attr.sbuild else None
    default_target = ":source_built_wheel" if sbuild_target else None
    if sbuild_target:
        console_scripts_override_attr = ""
        if repository_ctx.attr.sbuild_console_scripts_override:
            console_scripts_override_attr = "\n    console_scripts_override = True,"
        content.append(
            """
source_built_wheel(
    name = "source_built_wheel",
    src = {src},
    console_scripts = {console_scripts},{console_scripts_override_attr}
    visibility = ["//visibility:private"],
)
""".format(
                src = repr(sbuild_target),
                console_scripts = repr(repository_ctx.attr.sbuild_console_scripts),
                console_scripts_override_attr = console_scripts_override_attr,
            ),
        )

    # select_arms derives from prebuilds, so prebuilds alone decides.
    if prebuilds and not default_target:
        default_target = ":whl_missing"
        content.append(
            """
py_library(
    name = "whl_missing",
    srcs = [],
    target_compatible_with = ["@platforms//:incompatible"],
    visibility = ["//visibility:private"],
)
""",
        )

    # Index the platform-SELECTED wheel (the select chain's `:whl`), not an
    # arbitrary one: an arbitrary choice can pick a non-host wheel, forcing
    # Gazelle to fetch it — defeating lazy fetching and failing outright if
    # that wheel is unreachable/incompatible while the host's is valid.
    if prebuilds or default_target:
        gazelle_index_whl = ":whl"
    else:
        fail("Cannot identify a wheel or sbuild of {} to analyze for Gazelle indexing\n{}".format(repository_ctx.name, pprint(repository_ctx.attr)))

    content.append(
        """
select_chain(
   name = "whl",
   arms = {arms},
   default_target = {default_target},
   visibility = ["//visibility:public"],
)

filegroup(
    name = "gazelle_index_whl",
    srcs = {index_whl},
    visibility = ["//visibility:public"],
)
""".format(
            arms = indent(pprint(select_arms), "   ").lstrip(),
            default_target = repr(default_target),
            index_whl = indent(pprint([str(gazelle_index_whl)]), " " * 4).lstrip(),
        ),
    )

    post_install_patches = json.decode(repository_ctx.attr.post_install_patches) if repository_ctx.attr.post_install_patches else []
    post_install_patch_strip = repository_ctx.attr.post_install_patch_strip

    extra_deps = json.decode(repository_ctx.attr.extra_deps) if repository_ctx.attr.extra_deps else []
    extra_data = json.decode(repository_ctx.attr.extra_data) if repository_ctx.attr.extra_data else []

    compile_pyc_select = """select({
        "@aspect_rules_py//uv/private/pyc:is_precompile": True,
        "//conditions:default": False,
    })"""

    pyc_invalidation_mode_select = """select({
        "@aspect_rules_py//uv/private/pyc:is_unchecked_hash": "unchecked-hash",
        "@aspect_rules_py//uv/private/pyc:is_timestamp": "timestamp",
        "//conditions:default": "checked-hash",
    })"""

    # The selected wheel is a `whl_dist` (or the source-built fallback) that
    # carries its own layout as PyWheelMetadataInfo; the build rule reads it.
    install_attrs = """
    src = ":whl",
    compile_pyc = {compile_pyc},
    pyc_invalidation_mode = {pyc_invalidation_mode},""".format(
        compile_pyc = compile_pyc_select,
        pyc_invalidation_mode = pyc_invalidation_mode_select,
    )

    if post_install_patches:
        install_attrs += """
    patches = {patches},
    patch_strip = {strip},""".format(
            patches = repr(post_install_patches),
            strip = post_install_patch_strip,
        )

    # exclude_glob drives both the install action (--exclude-glob) and the
    # build rule's analysis-time filtering of the selected wheel's layout.
    if repository_ctx.attr.exclude_glob:
        install_attrs += """
    exclude_glob = {exclude_glob},""".format(
            exclude_glob = indent(pprint(repository_ctx.attr.exclude_glob), " " * 4).lstrip(),
        )

    content.append(
        """
whl_install(
    name = "actual_install",{attrs}
    visibility = ["//visibility:private"],
)""".format(attrs = install_attrs),
    )

    if extra_deps or extra_data:
        # When extra deps/data are needed, wrap in a py_library instead of alias
        content.append(
            """
py_library(
    name = "install",
    srcs = [],
    deps = [":actual_install"] + {extra_deps},
    data = {extra_data},
    visibility = ["//visibility:public"],
)
""".format(
                extra_deps = repr(extra_deps),
                extra_data = repr(extra_data),
            ),
        )
    else:
        content.append(
            """
alias(
    name = "install",
    actual = ":actual_install",
    visibility = ["//visibility:public"],
)
""",
        )

    content.append("""
exports_files(
    ["BUILD.bazel"],
    visibility = ["//visibility:public"],
)
""")

    repository_ctx.file("BUILD.bazel", content = "\n".join(content))

    return repository_ctx.repo_metadata(reproducible = True)

whl_install = repository_rule(
    implementation = _whl_install_impl,
    attrs = {
        "whls": attr.string(),
        "sbuild": attr.label(),
        "sbuild_console_scripts": attr.string_list(),
        "sbuild_console_scripts_override": attr.bool(),
        "post_install_patches": attr.string(default = ""),
        "post_install_patch_strip": attr.int(default = 0),
        "exclude_glob": attr.string_list(),
        "extra_deps": attr.string(default = ""),
        "extra_data": attr.string(default = ""),
    },
)
