"""Builds and serializes a protobuf message defined in greeting.proto.

The `greeting_pb2` module is generated by protobuf's `py_proto_library` and run
from a rules_py `py_binary`.
"""

from greeting_pb2 import Greeting


def make_greeting(recipient: str, times: int) -> Greeting:
    return Greeting(recipient=recipient, times=times)


def render(greeting: Greeting) -> str:
    return "\n".join(f"Hello, {greeting.recipient}!" for _ in range(greeting.times))


def main() -> None:
    greeting = make_greeting("rules_py", 2)
    # Round-trip through the wire format to exercise the protobuf runtime.
    restored = Greeting.FromString(greeting.SerializeToString())
    print(render(restored))


if __name__ == "__main__":
    main()
