"""awkward_cpp: scikit-build-core (CMake + ninja) + pybind11 sdist build."""

uv = use_extension("@aspect_rules_py//uv:extensions.bzl", "uv")
uv.declare_hub(hub_name = "pypi_crossbuild_awkward_cpp")
uv.project(
    default_build_dependencies = [
        "build",
        "cmake",
        "ninja",
        "pybind11",
        "scikit-build-core",
    ],
    hub_name = "pypi_crossbuild_awkward_cpp",
    lock = "//awkward_cpp:uv.lock",
    pyproject = "//awkward_cpp:pyproject.toml",
)
use_repo(uv, "pypi_crossbuild_awkward_cpp")
