load("//py:defs.bzl", "py_test")

package(default_testonly = True)

py_test(
    name = "test",
    srcs = [
        "__test__.py",
        "test.py",
        "//uv/private/gazelle_manifest/tools:generate.py",
    ],
    args = ["$(location :test.py)"],
    data = ["test.py"],
    imports = ["../tools"],
    main = "__test__.py",
    deps = [
        "@pypi//pytest",
    ],
)
